### ISSUE TITLE
Code Signing

### ISSUE THREAD

**Issue by Brendonovich** [spacedriveapp/spacedrive#100]
All releases should be codesigned!

**Comment by maxichrome** [comment]
does this apply on Linux based platforms? I'm not sure how that works there if at all, but I have an idea how it works on Windows/macOS

**Comment by Brendonovich** [comment]
That's a question for @oscartbeaumont

**Comment by oscartbeaumont** [comment]
I am fairly sure codesigning is not a requirement on Linux but we should do it anyway. I am also fairly sure that Linux codesigning won't require us to buy a certificate, we can just issue one and end-users will install it onto their system with Spacedrive if they want to verify the installation.

For future reference, it looks like [AppImage supports codesigning](https://docs.appimage.org/packaging-guide/optional/signatures.html). I think Snap do their own codesigning (I could be wrong on this) and idk about Flatpak.
