### ISSUE TITLE
'Expression tree is too large' when indexing

### ISSUE THREAD

**Issue by Brendonovich** [spacedriveapp/spacedrive#1009]
### Describe the bug

Indexing large locations can cause the following error:
```
Database Error: Error executing query: Unknown - Error occurred during query execution: ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("Expression tree is too large (maximum depth 1000)"))), transient: false })
```

### Reproduction

Index large location or something

### Expected behavior

Indexing succeeds

### Platform and versions

```Shell
Anything
```

### Additional context

I think this is probably something to do with creating too many db records in one query, will have to check the indexer logic

**Comment by utkubakir** [comment]
This is fixed right?

**Comment by oscartbeaumont** [comment]
I am fairly sure. It's caused by too many params to a single PCR query.
