### ISSUE TITLE
Landing page errors in Brave browser

### ISSUE THREAD

**Issue by McPizza0** [spacedriveapp/spacedrive#1025]
### Describe the bug

https://www.spacedrive.com/ does not open or work in brave browser
![image](https://github.com/spacedriveapp/spacedrive/assets/17185737/681f7758-de5e-4323-bd29-29f46fee97d6)

note: if brave shields are disabled, site renders correctly

### Reproduction

1. Install Brave
2. Go to https://www.spacedrive.com/
3. Page flash, then error

### Expected behavior

For the site to render correctly

### Platform and versions

```Shell
Not relevant
```

### Additional context

Brave is not reporting any detected items to block
But disabling shields renders the page correctly
![image](https://github.com/spacedriveapp/spacedrive/assets/17185737/d18d740a-26db-44ff-add0-7552c7ad79f0)

**Comment by McPizza0** [comment]
@Brendonovich 
When changing `Block fingerprinting` from `Aggressively block fingerprinting` (default) to just `block fingerprinting` (as per your screenshot) - site renders correctly

**Comment by Brendonovich** [comment]
That does break things, but `Block Fingerprinting` seems to be the default for me (I've never changed it).
Brave's settings do warn that aggressive blocking can break sites, but it would be nice to know why it breaks + if it's possible to fix.
<img width="549" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/14191578/9170ffb7-a8a4-4a65-aec9-9beae0babd99">

Taking a look at console logs it seems like WebGL stuff is failing to load, perhaps we rely on some external scripts that are being blocked?
<img width="490" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/14191578/26542c0c-de1f-451c-ae22-6036b338dd8b">
<img width="461" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/14191578/ac78e0fc-fa35-453f-86c2-65011c9994d8">

**Comment by HeavenVolkoff** [comment]
Also experience this, on [LibreWolf](https://librewolf.net/) (WebGL disabled by default):
<img width="1512" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/9082460/a4f69d4e-63f0-4803-8ef3-2773390eafaf">

This is most likely related to the recent changes made in #966. We should probably be doing some graceful error handling and just fall backing to the old background when WebGL is not available

**Comment by Brendonovich** [comment]
Apparently Brave blocks some WebGL features in aggressive blocking mode so that would make sense

**Comment by HeavenVolkoff** [comment]
Librewolf was fixed, but Brave still needs a bit more work as it doesn't actually disable WebGL, but most of the API returns invalid values on the `Aggressively block fingerprinting` mode
