### ISSUE TITLE
[ENG-815] Shortcuts page

### ISSUE THREAD

**Issue by utkubakir** [spacedriveapp/spacedrive#1112]
Let's show our shortcuts on a page (in settings).  They will be customizable/changeable in the future but for now just displaying them will do. We can section them by their place e.g.

* General
  * Mouse 4 & Alt + Left → Navigate back

* Explorer
  * Command + V → Paste

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-815](https://linear.app/spacedriveapp/issue/ENG-815/shortcuts-page)</sub>

**Comment by Raduc4** [comment]
assigned

**Comment by PineappleRind** [comment]
I took a go at it 
<img width="1018" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/65303441/95551fb1-7054-4ba1-be58-b854691a5e38">
