### ISSUE TITLE
[ENG-819] Add more categories to core

### ISSUE THREAD

**Issue by utkubakir** [spacedriveapp/spacedrive#1115]
We need to have them all functional. Feel free to create sub-issues from this if some are gonna need extra work/effort.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-819](https://linear.app/spacedriveapp/issue/ENG-819/add-more-categories-to-core)</sub>

**Comment by Brendonovich** [comment]
I think Databases is just database files like SQLite, it's already an `ObjectKind`
