### ISSUE TITLE
[ENG-795] Tooltip location is weird and triangle is wrong color

### ISSUE THREAD

**Issue by utkubakir** [spacedriveapp/spacedrive#1117]
![](https://uploads.linear.app/acbbe821-841d-473d-bf38-d1d995f656fb/8dfa44e6-0420-47ce-9354-c7181a2a32ba/0ee0bff8-6120-471c-906d-02615796f396?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjYmJlODIxLTg0MWQtNDczZC1iZjM4LWQxZDk5NWY2NTZmYi84ZGZhNDRlNi0wNDIwLTQ3Y2UtOTM1NC1jNzE4MWEyYTMyYmEvMGVlMGJmZjgtNjEyMC00NzFjLTkwNmQtMDI2MTU3OTZmMzk2IiwiaWF0IjoxNjkwOTk0ODg2LCJleHAiOjE2OTEwODEyODZ9.wYuiPJ07FHLCncYgjknTj3mdf_6ONEwKf0e5cfe44ng)

![](https://uploads.linear.app/acbbe821-841d-473d-bf38-d1d995f656fb/2f7fb417-b710-417d-bbd2-205bef42fdaf/baea306f-27f3-49ae-bd5e-1058ef4dd727?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjYmJlODIxLTg0MWQtNDczZC1iZjM4LWQxZDk5NWY2NTZmYi8yZjdmYjQxNy1iNzEwLTQxN2QtYmJkMi0yMDViZWY0MmZkYWYvYmFlYTMwNmYtMjdmMy00OWFlLWJkNWUtMTA1OGVmNGRkNzI3IiwiaWF0IjoxNjkwOTk0ODg2LCJleHAiOjE2OTEwODEyODZ9.PysYgN5p5vna6KgYFazNvilBSZmorQNfuBXfC0ghA0g)

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-795](https://linear.app/spacedriveapp/issue/ENG-795/tooltip-location-is-weird-and-triangle-is-wrong-color)</sub>

**Comment by Raduc4** [comment]
Hi, where are these components located? 
I can not really find them in the Desktop UI

**Comment by utkubakir** [comment]
> Hi, where are these components located? I can not really find them in the Desktop UI

`packages/ui/src/Tooltip.tsx`

**Comment by sarkartanmay393** [comment]
@utkubakir Hy, I just arrived and I think I can fix this issue. Do you want me to take on this task?

**Comment by utkubakir** [comment]
@sarkartanmay393 yes you can. Also not sure what happened to the images on the issue but here you go, might help :)

<img width="479" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/74243531/707eb317-fc17-4195-8ea7-001e47f11086">

P.S. This issue may have already been resolved
