### ISSUE TITLE
[ENG-801] Renaming file to a long name causes error

### ISSUE THREAD

**Issue by utkubakir** [spacedriveapp/spacedrive#1120]
![image.png](https://uploads.linear.app/acbbe821-841d-473d-bf38-d1d995f656fb/420a671c-7e24-48be-9da3-17983b68e0a6/44156e21-528a-4257-adac-2eeba44c4f97?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjYmJlODIxLTg0MWQtNDczZC1iZjM4LWQxZDk5NWY2NTZmYi80MjBhNjcxYy03ZTI0LTQ4YmUtOWRhMy0xNzk4M2I2OGUwYTYvNDQxNTZlMjEtNTI4YS00MjU3LWFkYWMtMmVlYmE0NGM0Zjk3IiwiaWF0IjoxNjg5NjIwMjQyLCJleHAiOjE2ODk3MDY2NDJ9.UWIXQTeijYBzgjhnFXD_h1KkbJSfUeEFgNlI470vgAY)

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-801](https://linear.app/spacedriveapp/issue/ENG-801/renaming-file-to-a-long-name-causes-error)</sub>

**Comment by ameer2468** [comment]
![Screenshot 2023-10-02 at 1.14.08 PM.png](https://uploads.linear.app/acbbe821-841d-473d-bf38-d1d995f656fb/9d0f798f-734d-4ac9-980f-e1fe90f46fb3/d9d61e7b-695e-4198-bb05-267abbec6644)


Need confirmation on this - was this a temp glitch or something? or rather, how long are we talking as I tested this right now.

**Comment by utkubakir** [comment]
issue is 3 months old so i guess this is fixed
