### ISSUE TITLE
[ENG-873] Ctrl c/v/d/x/z does nothing

### ISSUE THREAD

**Issue by utkubakir** [spacedriveapp/spacedrive#1150]
<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-873](https://linear.app/spacedriveapp/issue/ENG-873/ctrl-cvdxz-does-nothing)</sub>

**Comment by utkubakir** [comment]
@ameer2468

**Comment by ameer2468** [comment]
This has been done already.

Ctrl D is in my shortcuts PR.
