### ISSUE TITLE
[ENG-826] Remove auto suggest from inputs

### ISSUE THREAD

**Issue by utkubakir** [spacedriveapp/spacedrive#1152]
while creating a library & search etc.

see here for detailed feedback

[https://discord.com/channels/949090953497567312/1121730047993200640/1122789003708608614](https://discord.com/channels/949090953497567312/1121730047993200640/1122789003708608614)

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-826](https://linear.app/spacedriveapp/issue/ENG-826/remove-auto-suggest-from-inputs)</sub>

**Comment by Raghav-45** [comment]
Where can I find a Discord link? Coz i cant see what users have attached inside issues.
