### ISSUE TITLE
[ENG-947] Images and videos in the Inspector should have frame matching grid view

### ISSUE THREAD

**Issue by utkubakir** [spacedriveapp/spacedrive#1166]
Images and videos in the Inspector should have a frame that matches or closely resembles the grid view counterpart.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-947](https://linear.app/spacedriveapp/issue/ENG-947/images-and-videos-in-the-inspector-should-have-frame-matching-grid)</sub>

**Comment by utkubakir** [comment]
@jamie can we get more information on this? I don't really understand what it means

**Comment by Raghav-45** [comment]
hey @utkubakir and @jamiepine,

is that mean from this:

![Screenshot (67) 2](https://github.com/spacedriveapp/spacedrive/assets/77260113/5674cd72-7d20-48c3-865d-3eef9d067249)

to this:

![Screenshot (68) 2](https://github.com/spacedriveapp/spacedrive/assets/77260113/1c1ca4af-0e3c-4daf-8db0-fe9665470fc0)

is this issue about spacing?
