### ISSUE TITLE
[ENG-952] Change position of search bar

### ISSUE THREAD

**Issue by utkubakir** [spacedriveapp/spacedrive#1171]
The position of the search bar is awkward, it's never in the absolute center and appears incorrect. It may be worth considering right-justifying it, as it was nearly in the past.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-952](https://linear.app/spacedriveapp/issue/ENG-952/change-position-of-search-bar)</sub>

**Comment by utkubakir** [comment]
@niikeec is this fixed?

**Comment by niikeec** [comment]
> @niikeec is this fixed?
> 
> 

Has been centered to the topbar in this pr https://github.com/spacedriveapp/spacedrive/pull/1252
