### ISSUE TITLE
[ENG-956] Add "sister files" to inspector

### ISSUE THREAD

**Issue by utkubakir** [spacedriveapp/spacedrive#1175]
The Inspector should have tabs, one of them being "sister files" - a list of files that, when double-clicked, are revealed in the explorer.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-956](https://linear.app/spacedriveapp/issue/ENG-956/add-sister-files-to-inspector)</sub>

**Comment by Raghav-45** [comment]
> The Inspector should have tabs, one of them being "sister files" - a list of files that, when double-clicked, are revealed in the explorer.
> 
> <sub>From [SyncLinear.com](https://synclinear.com) | [ENG-956](https://linear.app/spacedriveapp/issue/ENG-956/add-sister-files-to-inspector)</sub>

Hey @utkubakir,

from what I understand, the concept of `sister files` seems similar to **duplicate** files.

Could you provide more information about what these `sister files` are? I'd love to contribute and help implement this feature if I can.

Looking forward to your response!

**Comment by utkubakir** [comment]
@Raghav-45 Yup sister files here means duplicate Objects. I don't we have a query which returns this yet though so that should be first thing to tackle
