### ISSUE TITLE
[ENG-1000] Layered icon should only show on top of Document icon

### ISSUE THREAD

**Issue by utkubakir** [spacedriveapp/spacedrive#1247]
we dont want this 

![image.png](https://uploads.linear.app/acbbe821-841d-473d-bf38-d1d995f656fb/1478bfe8-246d-4581-9808-7f7c9557cd74/6d25806c-04b2-4c0d-b33c-b502da583cb3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjYmJlODIxLTg0MWQtNDczZC1iZjM4LWQxZDk5NWY2NTZmYi8xNDc4YmZlOC0yNDZkLTQ1ODEtOTgwOC03ZjdjOTU1N2NkNzQvNmQyNTgwNmMtMDRiMi00YzBkLWIzM2MtYjUwMmRhNTgzY2IzIiwiaWF0IjoxNjkyOTEyMjA3LCJleHAiOjE2OTI5OTg2MDd9.tC_qXOWAhW-aXO8dD0nM72LJJplHywklOt1vJhNCEqk)

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-1000](https://linear.app/spacedriveapp/issue/ENG-1000/layered-icon-should-only-show-on-top-of-document-icon)</sub>

**Comment by PineappleRind** [comment]
<img width="110" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/65303441/b66b6883-efc5-42f6-a9a7-25bcec5ee7c8">

↑ so then this shouldn't show the JSON icon?

**Comment by jamiepine** [comment]
Just pushed a fix for this
