### ISSUE TITLE
Windows Install Doesnt Work

### ISSUE THREAD

**Issue by 0xEmma** [spacedriveapp/spacedrive#1317]
### Describe the bug

Error: The 'PlatformProvider' has not been mounted above the current 'usePlatform' call.

### Reproduction

Install on windows

### Expected behavior

works

### Platform and versions

```Shell
Windows 11
```

**Comment by HeavenVolkoff** [comment]
This was fixed in https://github.com/spacedriveapp/spacedrive/commit/1cae4fab53645daaec3a2618d137ce0884b7aaa6
