### ISSUE TITLE
[ENG-888] Media view should show current folder downward

### ISSUE THREAD

**Issue by utkubakir** [spacedriveapp/spacedrive#1379]
q: will we be able to go into a folder and have the option to only view that media in that folder instead of all the other folders/locations?

a: "it’s supposed to show you from the current folder downward, but it shows the whole location currently

happy to add a toggle to only show the current directory, when we fix the other bug"

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-888](https://linear.app/spacedriveapp/issue/ENG-888/media-view-should-show-current-folder-downward)</sub>

**Comment by PineappleRind** [comment]
<img width="317" alt="Screenshot 2023-10-11 at 10 07 27 AM" src="https://github.com/spacedriveapp/spacedrive/assets/65303441/9ae6fd58-ff09-41ae-bd54-004d37dd1284">

seems to be fixed

**Comment by utkubakir** [comment]
Thank you @PineappleRind (SyncLinear not working as usual)
