### ISSUE TITLE
[ENG-864] Create directory

### ISSUE THREAD

**Issue by jamiepine** [spacedriveapp/spacedrive#1380]
A context menu / top bar option to create a new folder in the explorer

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-864](https://linear.app/spacedriveapp/issue/ENG-864/create-directory)</sub>

**Comment by brxken128** [comment]
@gedeondoescode is wanting to take this issue over and I'm fine with that 🙏🏻

**Comment by brxken128** [comment]
Done in #1458.
