### ISSUE TITLE
[ENG-1131] pathsCount should take "show hidden files" into consideration, so the explorer view height is correct.

### ISSUE THREAD

**Issue by niikeec** [spacedriveapp/spacedrive#1383]
<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-1131](https://linear.app/spacedriveapp/issue/ENG-1131/pathscount-should-take-show-hidden-files-into-consideration-so-the)</sub>

**Comment by PineappleRind** [comment]
So this means in `location/$id.tsx`, pathsCount should be recalculated when explorerSettings.showHiddenFiles and PathsInfiniteQuery change (like `items`)?

**Comment by niikeec** [comment]
> So this means in `location/$id.tsx`, pathsCount should be recalculated when explorerSettings.showHiddenFiles and PathsInfiniteQuery change (like `items`)?
> 
> Also, is there a downside to using items.length instead of querying pathsCount?

This has been resolved in #1398 

As for the pathsCount querying, yes there is a downside to just using items.length. With the count of paths, we can make the height of the explorer view as if all items were already fetched which means you can scroll through the whole set in one go, rather than having the height adjusted each time you fetch more, and with that having to readjust your cursor and start scrolling again.
