### ISSUE TITLE
[ENG-870] Deleting a folder should not say "Deleted 1 file"

### ISSUE THREAD

**Issue by utkubakir** [spacedriveapp/spacedrive#1384]
It should calculate how many items are in it or even "deleted {folderName}" might work

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-870](https://linear.app/spacedriveapp/issue/ENG-870/deleting-a-folder-should-not-say-deleted-1-file)</sub>

**Comment by Milo123459** [comment]
im gonna try this
