### ISSUE TITLE
Redundant active-development notice in README

### ISSUE THREAD

**Issue by maxichrome** [spacedriveapp/spacedrive#143]
In the following image, there are two somewhat-redundant active-development notices. Let's discuss if-or-how we'd like to reconcile/simplify these.

![Snapshot of about three paragraphs of the Spacedrive README file, with a notice toward both the top and bottom that identically state Spacedrive is in active development, with the bottom notice having an extra clause.](https://user-images.githubusercontent.com/54680617/167995766-13d56070-5280-4e09-b0d9-a3697a96dd3b.png)

_Originally posted by @yadunandanbhat in https://github.com/spacedriveapp/spacedrive/discussions/142#discussioncomment-2734919_

**Comment by maxichrome** [comment]
@jamiepine would love to hear your thoughts

**Comment by jamiepine** [comment]
already fixed
