### ISSUE TITLE
wrong file sizes

### ISSUE THREAD

**Issue by KMJ-007** [spacedriveapp/spacedrive#1442]
### Describe the bug

was trying out the app to fix some issue,

the size of the folders and files are showing wrong

<img width="1263" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/86996507/59f314a7-c2e0-4945-9ff4-c703420294d6">

through finder:
<img width="298" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/86996507/3ccfc625-7c11-4895-a54c-1bdab3700b7b">

### Reproduction

1. go to folder
2. sort them by sizes
3. view list layout
4. see size of folder

### Expected behavior

file size should be correct 

### Platform and versions

```Shell
sion
8.7.1
cargo 1.71.1 (7f1d04c00 2023-07-29)
rustc 1.71.1 (eb26296b5 2023-08-03)

using macos 14.0 (23A344) AIR m1
```

**Comment by fogodev** [comment]
We currently don't support directory sizes for ephemeral locations. As it would be kinda costly to recalculate over and over again. But maybe this can be mitigated with some in memory caching.

**Comment by utkubakir** [comment]
I created an issue for this to hide folder sizes on ephemeral locations.
