### ISSUE TITLE
Use of a deprecated insecure library, libssl1.1, preventing use on ubuntu 22.04

### ISSUE THREAD

**Issue by MulverineX** [spacedriveapp/spacedrive#1474]
### Describe the bug

```
mulverine@zhulong:~$ spacedrive
spacedrive: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
Related Issues: https://github.com/dotnet/sdk/issues/24759 https://github.com/tauri-apps/tauri/issues/4470 

### Platform and versions

```Shell
PopOS 22.04 (ubuntu jammy flavor by system76)
```

**Comment by HeavenVolkoff** [comment]
Thanks for reporting this issue, I am closing this to centralizing all the deb issues in https://github.com/spacedriveapp/spacedrive/issues/1512
