### ISSUE TITLE
Missing application shortcut on linux

### ISSUE THREAD

**Issue by MulverineX** [spacedriveapp/spacedrive#1475]
### Describe the bug

Upon installation, no .desktop file is generated & provided.

### Platform and versions

```Shell
PopOS 22.04 (system76 ubuntu jammy flavor)
```

**Comment by imkrunal** [comment]
Can confirm this happends on Ubuntu 22.04 as well. Any work arounds for now? @MulverineX

**Comment by MulverineX** [comment]
afaict not any good ones, I'd rather not screw up my distro. If I happen upon a decent workaround I'll post it here. @imkrunal 

One thing that the team could opt to do for now is to release with flatpak, that way using a sandboxed libssl1.1

**Comment by HeavenVolkoff** [comment]
Is this happening when using the `.appimage` or the ` .deb` release?

Flatpak's release is planned, but due to it not being natively supported by tauri, it will require some work and is low priority for the moment, hope to have it done by beta release

**Comment by imkrunal** [comment]
I have used the .deb release.

**Comment by HeavenVolkoff** [comment]
Odd, when I tested the `.deb` it did create a `.desktop` file. However, there are currently other issues with the `.deb` release, so this is probably one more. I will close this issue in favor of https://github.com/spacedriveapp/spacedrive/issues/1512, because it is where I am centralizing all the `.deb` release issues

**Comment by joezhouchenye** [comment]
Ubuntu 22.04.

The .desktop file is indeed created in /usr/share/applications. However, it should be created in ~/.local/share/applications instead.

**Comment by HeavenVolkoff** [comment]
@joezhouchenye The correct location for `.desktop` files when installed by system packages is `/usr/share/applications`. `~/.local/share/applications ` is exclusively for user installed programs, outside the distribution package manager.

https://www.debian.org/doc/debian-policy/ch-opersys.html#menus
https://wiki.archlinux.org/title/Desktop_entries#Application_entry

**Comment by joezhouchenye** [comment]
Then, some permission or owner problem I think. I cannot find it in the application menu on Ubuntu 22.04.

![image](https://github.com/spacedriveapp/spacedrive/assets/59191277/71e9c111-74f5-4aa6-8020-00b25a50d62d)

The owner and permission look different from other `.desktop` files in `/usr/share/applications`

**Comment by joezhouchenye** [comment]
I managed to get it shown in the application menu by copying it to the user applications folder and using chown and chmod.
