### ISSUE TITLE
[ENG-1229] 'Show Hidden Files' toggle is not working

### ISSUE THREAD

**Issue by Panchajanya1999** [spacedriveapp/spacedrive#1478]
### Describe the bug

From 'Explorer Display' -> 'Explorer' -> 'Show Hidden Files', it stays on ticked even after unticking it.
Seems like this option is no-op since even after enabling it, I can't see my hidden files in the folder.

### Reproduction

1. Go to Explorer Display
2. Check Explorer
3. Tick/Untick Show Hidden Files
4. It stays ticked and is no-op

### Expected behavior

Supposed to be functional and remember user's choice.

### Platform and versions

```Shell
Spacedrive - Alpha 0.1.0
Machine - Archlinux
```

**Comment by rondDev** [comment]
> I can't see my hidden files in the folder.

It doesn't seem like hidden files work for me either.

Version: Alpha 0.1.0
OS: Windows 11 22H2

**Comment by Panchajanya1999** [comment]
Thanks for the heads-up.

**Comment by j1philli** [comment]
Same here!
![CleanShot 2023-10-12 at 12 08 36](https://github.com/spacedriveapp/spacedrive/assets/3744255/72ce4c75-332e-4ea6-bd1d-3341893781ec)
![CleanShot 2023-10-12 at 12 08 49](https://github.com/spacedriveapp/spacedrive/assets/3744255/8a235da6-baf6-4854-ad23-235db218a9f9)
