### ISSUE TITLE
Missing `libssl.so.1.1` on Ubuntu 22.04

### ISSUE THREAD

**Issue by hobofan** [spacedriveapp/spacedrive#1481]
### Describe the bug

App doesn't open up due to missing library.

### Reproduction

- Installed the package from the `.deb` on the website
- Tried to run directly from a launcher -> nothing opened
- Tried running from a terminal, and I get the following error message:
```
spacedrive: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

### Platform and versions

```Shell
Ubuntu 22.04
```

### Additional context

I know that there are some manual remedies out there to fix this, but this seems like a case of incomplete dependencies specified in the `.deb` (and/or wrong versions for this distribution).

**Comment by HeavenVolkoff** [comment]
Thanks for reporting this issue, I am closing this to centralizing all the deb issues in https://github.com/spacedriveapp/spacedrive/issues/1512
