### ISSUE TITLE
[Linux] Failed to create GBM buffer of size: Permission denied

### ISSUE THREAD

**Issue by Herklos** [spacedriveapp/spacedrive#1486]
### Describe the bug

Just after 0.1.0 installation, at first launch I get the following errors:
![image](https://github.com/spacedriveapp/spacedrive/assets/10454670/49d2b162-98a2-4322-ad7c-8ebdda6be2b5)

### Reproduction

1. Install deb file on an Ubuntu 22.0.4 (with i3 ?)
2. launch spacedrive

### Platform and versions

```Shell
pnpm 8.7.1
cargo 1.72.1 (103a7ff2e 2023-08-15)
rustc 1.72.1 (d5c2e9c34 2023-09-13)
```

### Stack trace

```Shell
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1400x725: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1400x725: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1400x725: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
```

**Comment by HeavenVolkoff** [comment]
Do you have a bare metal Linux install? Or is it a virtualized/docker/WSL?

**Comment by Herklos** [comment]
Yes, it's a bare metal Linux.

**Comment by HeavenVolkoff** [comment]
What graphics card do you have and what drivers (mesa, nvidia proprietary, AMDGPU) are you using? Are you able to open spacedrive using the following command: `env LIBGL_ALWAYS_SOFTWARE=1 spacedrive`

**Comment by Herklos** [comment]
I have an nvidia proprietary with drivers installed. I get the same result with this environment var `LIBGL_ALWAYS_SOFTWARE=1` set.

**Comment by HeavenVolkoff** [comment]
Did you try the `appimage` release, does it behave similarly? The deb release currently has some specific bugs that I am working toward fixing atm: #1512. Maybe this is one more specific deb issue

**Comment by Herklos** [comment]
The Appimage works fine thanks!
