### ISSUE TITLE
[ENG-1155] Improve when adding a new location (trigger UI re-render)

### ISSUE THREAD

**Issue by utkubakir** [spacedriveapp/spacedrive#1487]
When adding a Location, indexing/identifying jobs do not seem to be causing a UI re-render, shows as "empty folder" if Location was opened at start of job.

* should also show a indexing indicator or something similar.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-1155](https://linear.app/spacedriveapp/issue/ENG-1155/improve-when-adding-a-new-location-trigger-ui-re-render)</sub>

**Comment by bloodrizer** [comment]
Can confirm the same issue
