### ISSUE TITLE
Enable Github Sponsors

### ISSUE THREAD

**Issue by MinmoTech** [spacedriveapp/spacedrive#150]
### Describe the bug

In the [faq](https://www.spacedrive.com/faq) you list Github Sponsors as an income source.
I'd like to support the project with github sponsors, but it's not enabled yet.

### Platform and versions

```shell
Using github
```

**Comment by maxichrome** [comment]
We won't enable GitHub sponsors for now, for logistics reasons. If you wish to contribute financially, please check out our [Open Collective](https://opencollective.com/spacedrive)!

I'll link a change to this issue to update the language in our FAQ, though. Thanks for reporting that discrepancy ;)

**Comment by AlyxPink** [comment]
Hey there! Just wondering if two years later, enabling GitHub Sponsors could be an option, or it's still a logistic nightmare? 🙇
