### ISSUE TITLE
Light mode tooltips on Overview wrong background

### ISSUE THREAD

**Issue by PineappleRind** [spacedriveapp/spacedrive#1504]
### Describe the bug

<img width="234" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/65303441/e8e42242-5441-4ab4-83f7-861f050ef426">

The tooltips on the Overview page have the dark mode background

### Reproduction

1. Turn on Light mode.
1. Navigate to the Overview page.
1. Hover over the *i* next to any of the size indicators.
1. Observe the tooltip's background

### Expected behavior

It should look like the one on Settings > Locations: 

<img width="363" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/65303441/82b5aa5f-9ad4-4dd7-bba7-9d78bfbbcaec">

### Platform and versions

```Shell
8.8.0
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
rustc 1.70.0 (90c541806 2023-05-31)
```

Spacedrive v0.1.0 - fdc3c30
MacOS 13.3.1 Ventura

### Additional context

Later I can investigate this more (and maybe write a fix)

**Comment by mmattbtw** [comment]
I can pick this up if nobody's working on it already :-)

**Comment by ameer2468** [comment]
This has been fixed and merged today, thank you!
