### ISSUE TITLE
[ENG-1251] Add shortcut for toggling hidden files

### ISSUE THREAD

**Issue by utkubakir** [spacedriveapp/spacedrive#1513]
it's ⌘⌥ for macOS looks like, do look into it tho. (for windows and linux too if available)

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-1251](https://linear.app/spacedriveapp/issue/ENG-1251/add-shortcut-for-toggling-hidden-files)</sub>

**Comment by fogodev** [comment]
On Linux it's `Ctrl H`

**Comment by ameer2468** [comment]
According to this:  there is no specific shortcut to toggle hidden files on Windows. It's just a checkbox.

https://pureinfotech.com/show-hidden-files-windows-11-file-explorer/#:~:text=Open%20File%20Explorer%20on%20Windows,check%20the%20Hidden%20items%20option.
