### ISSUE TITLE
Mouse x1/x2 triggers twice on windows

### ISSUE THREAD

**Issue by kimidaisuki22** [spacedriveapp/spacedrive#1536]
### Describe the bug

When I press forward/backward by mouse, it triggers twice, one for key down, and one for key up.

### Reproduction

Start, click C:, click D:, then try to go back and forward with mouse x1/x2, It just happened.
It does not always happen, but very often.

### Platform and versions

```Shell
v0.1.0 - fdc3c30 Windows from www.spacedrive.com
```

### Additional context

I'm not logged in.

**Comment by ameer2468** [comment]
This has been fixed. Thank you for the report.
