### ISSUE TITLE
Crash Report when opening a folder with lots of pictures

### ISSUE THREAD

**Issue by omagdy7** [spacedriveapp/spacedrive#1551]
### Describe the bug

Opening a folder with lots of pictures(400+) allocates huge amount of memory and uses the CPU extensively and the app just crashes

### Reproduction

1. Find a folder with a lot of pictures
2. Open the folder

### Expected behavior

The app opens the folder without crashing

### Platform and versions

```Shell
OS: Arch Linux
Kernel: 6.1.52-1-lts
pnpm version: 8.7.4
cargo version: 1.71.1
rustc version: 1.71.1
```

**Comment by HeavenVolkoff** [comment]
Hi, thanks for reporting this issue. This should have already been fixed by #1523, which is included in release 0.1.1, and will be further improved by #1585. Could you test the latest release to check if the issue stopped occurring?

**Comment by omagdy7** [comment]
It doesn't crash now but it's very laggy when scrolling or interacting with the program in general.

**Comment by HeavenVolkoff** [comment]
Thanks for testing. There are some performance improvements already implemented which will be included in the next release, and we are working hard to improve the experience overall. I will close this issue, but feel free to open a new one if you have any other problems with future releases.
