### ISSUE TITLE
Tag color picker switches back to first tag when releasing the mouse

### ISSUE THREAD

**Issue by wolleydev** [spacedriveapp/spacedrive#1564]
### Describe the bug

When selecting a tag color with the color picker, as soon as you release the mouse, the color picker window is closed and the first tag in the list gets selected instead of the view staying on the tag you were editing

https://github.com/spacedriveapp/spacedrive/assets/130301036/b4bed718-3b9b-4f2e-ad69-bda18b1db0a7

### Reproduction

1. Create a tag or select one from the list
2. Open the color picker
3. Drag the cursor in either areas (hue slider or color space)
4. As soon as you release the mouse, the color picker window is closed and the first tag in the list gets selected instead of the view staying on the tag you were editing

### Expected behavior

The color picker should stay open and the current tag should remain selected

### Platform and versions

```Shell
Windows 10 Pro N 22H2 (build 19045.3570)
```

**Comment by ameer2468** [comment]
This has been fixed, thank you.
