### ISSUE TITLE
MOUSE4 and MOUSE5 don't work when hovering a link on macOS

### ISSUE THREAD

**Issue by innocenzi** [spacedriveapp/spacedrive#1568]
### Describe the bug

<kbd>MOUSE4</kbd> and <kbd>MOUSE5</kbd> are used for back/forward navigation and seem to work properly in Spacedrive, except when the mouse is hovering a link (so, navigation items on the sidebar, or a file or directory in the main panel).

### Reproduction

On file/directories:
1. Put mouse over a directory or file
2. Press <kbd>MOUSE4</kbd> or <kbd>MOUSE5</kbd>
3. The navigation doesn't happen

On sidebar:
1. Put mouse over a link in the sidebar
2. Press <kbd>MOUSE4</kbd> or <kbd>MOUSE5</kbd>
3. Navigation happens like a <kbd>LEFT CLICK</kbd> was used

### Expected behavior

Back/forward navigation should always happen, whether the mouse is hovering something or not.

### Platform and versions

```Shell
v0.1.0 - bc38cf4
```

(On a side note: I'm actually on v0.1.1, and indeed on `bc38cf4`. Seems like the version number isn't properly updated)

**Comment by innocenzi** [comment]
Related (but not the same): https://github.com/spacedriveapp/spacedrive/issues/1536

**Comment by ameer2468** [comment]
This has been fixed - thank you for the report.
