### ISSUE TITLE
MacOS copy past not working

### ISSUE THREAD

**Issue by kcoderhtml** [spacedriveapp/spacedrive#1572]
### Describe the bug

Command V and Command C don't seem to work. The edit menu seems to be intercepting them.

### Reproduction

Copy a file and try to paste with Command V

### Expected behavior

The file should have copied.

### Platform and versions

```Shell
MacOS Ventura 13.5.1 (22G90)
```

**Comment by ameer2468** [comment]
This has been addressed, thank you for the report.
