### ISSUE TITLE
"Processing media files" gets stuck

### ISSUE THREAD

**Issue by OliverCole** [spacedriveapp/spacedrive#1588]
### Describe the bug

I left it adding a location for about 10 hours, and came back to it 'stuck' on "2 of 9607 media files processed". Restarting Spacedrive makes it jump forward 5-20 files - so I'm currently on "90 of 9607".

There's nothing interesting I can see in the logs.

### Reproduction

1. Add location with media files.
2. "Processing media files" step gets stuck
3. Restart Spacedrive
4. "Processing media files" advances a few files, gets stuck again

### Expected behavior

1. Add location with media files.
2. "Processing media files" step completes

### Platform and versions

```Shell
Release Alpha 0.1.1, Windows 10.
```

**Comment by HeavenVolkoff** [comment]
This should have been fixed by https://github.com/spacedriveapp/spacedrive/pull/1585 and https://github.com/spacedriveapp/spacedrive/issues/1607, which will be included on the next update
