### ISSUE TITLE
[ENG-1290] Changelog in-app

### ISSUE THREAD

**Issue by jamiepine** [spacedriveapp/spacedrive#1592]
I think we should somehow embed the change log in the settings screen of the app. 

* When new update is installed we should show a toast on first startup with the version number and maybe a tagline for the update (that'd be awesome)
* It would be nice not to have to copy/paste the changelog 3 times, for docs, in-app, and GH release, maybe we could single source of truth it from our docs using a script? Wild idea. Or a 3rd party to help with managing changelogs, must exist.

Here's an example of the notification with the sexy tagline to entice people to try new features.

> **Updated successfully, you're on version 0.1.2**
>
> Enjoy faster thumbnail generation and a plethora of bug fixes.
> *\[View Changelog\] \[Got it\]*

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-1290](https://linear.app/spacedriveapp/issue/ENG-1290/changelog-in-app)</sub>

**Comment by Brendonovich** [comment]
**Toast on first startup**: Easy
**Tagline**: Put inside YAML frontmatter within an HTML comment at the top of the release
```
<--! # start of comment
---  # start of frontmatter
tagline: "This is a tagline that people on GitHub will never see!"
---
-->
```

**Source of truth**: GitHub Releases
**In docs**: Server-side render using ISR and path invalidation (App dir would make this really nice)
