### ISSUE TITLE
Adding media files with errors: Had an error generating thumbnail

### ISSUE THREAD

**Issue by bambooom** [spacedriveapp/spacedrive#1614]
### Describe the bug

I'm adding a folder of photos as a new location to the app.
And I found that the job completed with errors. 
![Screenshot 2023-10-18 at 01 54 09](https://github.com/spacedriveapp/spacedrive/assets/14840170/1a30342d-64a4-4afa-a5e0-4229e9b963f4)

Here shows many error with
> Had an error generating thumbnail for "xxxxx/pic.webp"

![Screenshot 2023-10-18 at 01 53 19](https://github.com/spacedriveapp/spacedrive/assets/14840170/38df35d3-bf7a-4d2e-8083-30d3141d3598)

There are several webp photos inside this folder. And all the above errors are occured with webp.
 

### Reproduction

1. Click "Add Location"
2. Choose a folder full of photos.
3. Enable "Only Images" option in Advanced settings
4. Click Add and wait for the job to be completed

### Expected behavior

Completed with no errors

### Platform and versions

```Shell
I'm using Version 0.1.1 (20231013.100750) on MacBook Pro with Apple M1 Pro chip.
```

**Comment by brxken128** [comment]
Are you able to send a sample of one of these images? We use `webp` for reading and writing our thumbnails, so it's either an issue somewhere else in our codebase or an issue with the files themselves.

**Comment by bambooom** [comment]
@brxken128 

Here's several example images. Thanks!

[webp-error-images.zip](https://github.com/spacedriveapp/spacedrive/files/13030002/webp-error-images.zip)

**Comment by HeavenVolkoff** [comment]
So, webp thumbnail is support, but it was disabled for some reason. I will open a PR fixing this. Thanks, @bambooom, for reporting this issue
