### ISSUE TITLE
Website crash

### ISSUE THREAD

**Issue by tdhuan** [spacedriveapp/spacedrive#1627]
### Describe the bug

[Screencast from 10-19-2023 05:18:09 PM.webm](https://github.com/spacedriveapp/spacedrive/assets/35454344/849f76c3-ccf9-4694-b3b6-1910a40f24b6)

### Platform and versions

```Shell
Ubuntu 22.04
Chrome Version 117.0.5938.132 (Official Build) (64-bit)
```

### Stack trace
![Screenshot from 2023-10-20 12-05-58](https://github.com/spacedriveapp/spacedrive/assets/35454344/b73ee9f8-edcb-4691-a719-51a4bc5ae28f)

_No response_

**Comment by HeavenVolkoff** [comment]
Hello, thanks for reporting the issue, could please check if there is any error in the console (F12), and screenshot it/paste the stack trace here please

**Comment by brxken128** [comment]
That is odd, I have WebGL disabled entirely and the page runs fine on Firefox. I see you're using a fair amount of extensions (some being ad/tracker/privacy focused by the looks of it) - could you try disabling them and visiting the site again?

I think incognito mode also disables extensions, but I'm not familiar enough with Chrome to know for sure.

**Comment by HeavenVolkoff** [comment]
@tdhuan can you check if this [link](https://spacedrive-landing-git-workaround-broken-webgl-spacedrive.vercel.app/) works on your Chrome

**Comment by HeavenVolkoff** [comment]
Hun... ok, this problem is a bit more involved, your environment does support WebGL it seems, but not the full capabilities needed for us to render the space background, I will need to implement some error handling when instantiating the `Space` component itself.

**Comment by IsomerX** [comment]
Hey @tdhuan Can you please check if this works for you https://get.webgl.org/ so we can rule out if your browser is atleast able to use webgl.

**Comment by brxken128** [comment]
> Hey @tdhuan Can you please check if this works for you https://get.webgl.org/ so we can rule out if your browser is atleast able to use webgl. Also, do you have more than 1 graphic card?

Some browsers/configs specifically disable `webgl` due to it being a great attack vector which can produce a _very_ unique fingerprint for telemetry, targeted advertisements and other forms of web tracking

**Comment by HeavenVolkoff** [comment]
@tdhuan, I implemented some new changes, could you try to see if it works now?
https://spacedrive-landing-git-workaround-broken-webgl-spacedrive.vercel.app/
