### ISSUE TITLE
Adding Location bug 🐞

### ISSUE THREAD

**Issue by Crushoverride007** [spacedriveapp/spacedrive#1683]
### Describe the bug

- When adding a location "Pictures" folder

</br>
<p align="center">
  <img src="https://github.com/spacedriveapp/spacedrive/assets/45631812/b21255ab-e150-4f32-bac0-489cd96eb137" />
</p>

- Also while trying to add any other locations while checking the boxes "Open new location once added" and in the advanced settings for file indexing rules "No OS protected" it generates this error,

</br>

<p align="center">
  <img src="https://github.com/spacedriveapp/spacedrive/assets/45631812/fdcb4e25-747f-4346-b9fb-2cb2c2c84bba" />
</p>

### Reproduction

1. go to **Locations** > **Add Location**
2. Choose the folder you want 
3. Check the boxes **"Open new location once added"** and in the advanced settings for file indexing **"No OS Protected"**

### Platform and versions

```Shell
Model Name: MacBook Pro
Chip      : Apple M1
OS        : macOS 14.0 (23A344)
```

**Comment by utkubakir** [comment]
Can confirm the bug, we will fix this asap

**Comment by utkubakir** [comment]
You can go to Privacy > Full Disk Access to make it work for now. it's tracked here https://github.com/spacedriveapp/spacedrive/issues/1740
