### ISSUE TITLE
(Uninformed) application hang on first run

### ISSUE THREAD

**Issue by headquarter8302** [spacedriveapp/spacedrive#1717]
### Describe the bug

When the application first starts, nothing is loading in, the libraries, thumbnails, files, etc. This is due to Spacedrive indexing and generating the necessary thumbnails before anything loads. There's one issue, this is never informed to the user, and may cause unnecessary issue reports and inconveniences that may arise in the future.

I suggest either progressively updating the view while the DB is being created, or create an informative notification to tell the user that Spacedrive is currently building the object database.

### Reproduction

1. Install the app using the installer.
2. Go through the OOBE as normal.
3. **_Nothing will appear_. Elevated CPU and disk usage is noted just right after the OOBE.**
4. Reopen the app.
5. Everything should load as normal

### Expected behavior

Everything to appear.
Or...
A modal telling me to wait for Spacedrive to do its thing.

### Platform and versions

```Shell
GitHub release Alpha 0.1.2 MSI installer
Windows 10 22H2 19045
```

**Comment by utkubakir** [comment]
All of this should be instant actually, can you send us a video on this?

**Comment by headquarter8302** [comment]
Let me uninstall the app first and do a thorough cleanup, I'll see if this happens again or if this was a quirk with my environment

**Comment by headquarter8302** [comment]
Also, is the `.spacedrive` file on some folders normal behaviour? Because those are never cleaned up when the app closes and when I uninstall it

**Comment by headquarter8302** [comment]
Also this happened on reinstallation
![image](https://github.com/spacedriveapp/spacedrive/assets/65797058/9df65a57-ff66-4c7e-b4b4-70a3caa7f021)

**Comment by utkubakir** [comment]
> Also, is the `.spacedrive` file on some folders normal behaviour? Because those are never cleaned up when the app closes and when I uninstall it. They seem to contain JSON data of a library

We don't have a good uninstall process yet but you should be able to just link your old library again easily.

And no clue on the setup error 😕

**Comment by headquarter8302** [comment]
Weird, it seems that it was just my CPU and drive choking on Spacedrive suddenly eating cycles while it was busy doing something else. The files takes about 2-3 seconds to pop up on this reinstall but with near no processor resource being used by other apps.

Now it works just fine, thanks for the help!
