### ISSUE TITLE
Cant see size of a folder

### ISSUE THREAD

**Issue by Z3rio** [spacedriveapp/spacedrive#1727]
### Describe the bug

![image](https://github.com/spacedriveapp/spacedrive/assets/54480523/4744ea79-256e-4cbf-9bd8-9d4df79b006b)

Folder sizes are never shown.
It would be fairly nice to be able to sort by folder sizes and overall see them.

### Reproduction

Just open any directory that contains folders.

### Expected behavior

I would expect to be able to see the folder size and to be able to sort by it.

### Platform and versions

I personally use Windows, Im unsure if Mac already has support for this.

**Comment by utkubakir** [comment]
We currently don't support folder sizes for ephemeral locations as we can't calculate it on the go, normal locations (indexed) should display accurate folder size without any problems.

**Comment by Z3rio** [comment]
There are plenty of other programs such as [FolderSize](https://foldersize.sourceforge.net/) which do this without any issues.
Are you sure that this isn't planned at all? As it would be a great addition

**Comment by utkubakir** [comment]
> There are plenty of other programs such as [FolderSize](https://foldersize.sourceforge.net/) which do this without any issues. (Yes this is old, but works without any noticeable performance hit, I personally use it daily)
> 
> Are you sure that this isn't planned at all? As it would be a great addition

As I said, we display folder sizes for indexed locations already. If it's possible to do it in the future, we will do it for ephemeral locations also, it's just not a priority right now as the right way to use Spacedrive is about indexing your location

**Comment by Z3rio** [comment]
> > There are plenty of other programs such as [FolderSize](https://foldersize.sourceforge.net/) which do this without any issues. (Yes this is old, but works without any noticeable performance hit, I personally use it daily)
> > Are you sure that this isn't planned at all? As it would be a great addition
> 
> As I said, we display folder sizes for indexed locations already. If it's possible to do it in the future, we will do it for ephemeral locations also, it's just not a priority right now as the right way to use Spacedrive is about indexing your location

Ah, sorry, I misunderstood your last message then, I interpreted it as not being supported, nor going to be supported.
I'll have a look at indexing locations then, thank you.
