### ISSUE TITLE
"String must contain..." when closing tag window

### ISSUE THREAD

**Issue by JohannKaspar** [spacedriveapp/spacedrive#1769]
### Describe the bug

When I open the "New Tag" Window and click on "Close" without any cahnges made, I get the warning "String must contain at least 1 character(s)". Clicking on "Close" a second time actually closes the window.

### Expected behavior

I would expect to for the window to be closed without a warning.

### Platform and versions

```Shell
Spacedrive for macOS v0.1.2 - 83538f2
```

**Comment by brah2008** [comment]
It seems like there might be a validation issue in the code that checks whether the string in the "New Tag" window contains at least one character before closing the window. This validation check is triggering a warning even when no changes are made.

To correct this bug, you may need to modify the code responsible for handling the "Close" button action in the "New Tag" window. Here are the general steps you can take:

1. Locate the code that handles the "Close" button click event.

2. Check if there is a validation condition that requires the string to contain at least one character.

3. If such a condition exists, modify it to exclude the validation when no changes are made.

4. Test the application to ensure that the warning is not displayed when closing the window without making any changes.

Without access to the actual code, I can only provide general guidance. If you can share the relevant code snippet or provide more details about the code handling the "Close" button in the "New Tag" window, I might be able to provide more specific assistance.
