### ISSUE TITLE
List build dependencies in CONTRIBUTING.md for system that are not supported by setup script

### ISSUE THREAD

**Issue by jack9603301** [spacedriveapp/spacedrive#1781]
### Describe the bug

An error is reported when compiling on Linux From Scratch with the following error:

```
jack@media-server ~/lfswork/spacedrive (main)> cargo build --release
warning: skipping duplicate package `test-macros` found at `/home/jack/.cargo/git/checkouts/prisma-engines-8e1416dd0e571d11/45b026c/libs/test-macros`
warning: skipping duplicate package `test-setup` found at `/home/jack/.cargo/git/checkouts/prisma-engines-8e1416dd0e571d11/45b026c/libs/test-setup`
   Compiling blake3 v1.5.0
   Compiling libwebp-sys v0.9.4
   Compiling sd-prisma v0.1.0 (/home/jack/lfswork/spacedrive/crates/prisma)
   Compiling libp2p-quic v0.9.3
error[E0583]: file not found for module `prisma`
 --> crates/prisma/src/lib.rs:2:1
  |
2 | pub mod prisma;
  | ^^^^^^^^^^^^^^^
  |
  = help: to create the module `prisma`, create file "crates/prisma/src/prisma.rs" or "crates/prisma/src/prisma/mod.rs"
  = note: if there is a `mod prisma` elsewhere in the crate already, import it with `use crate::...` instead

error[E0583]: file not found for module `prisma_sync`
 --> crates/prisma/src/lib.rs:4:1
  |
4 | pub mod prisma_sync;
  | ^^^^^^^^^^^^^^^^^^^^
  |
  = help: to create the module `prisma_sync`, create file "crates/prisma/src/prisma_sync.rs" or "crates/prisma/src/prisma_sync/mod.rs"
  = note: if there is a `mod prisma_sync` elsewhere in the crate already, import it with `use crate::...` instead

For more information about this error, try `rustc --explain E0583`.
error: could not compile `sd-prisma` (lib) due to 2 previous errors
```

### Reproduction

cargo build --release

### Expected behavior

Compiled normally

### Platform and versions

```Shell
jack@media-server ~/lfswork/spacedrive (main) [SIGINT]> pnpm --version && cargo --version && rustc --version
8.10.5
cargo 1.75.0-nightly (708383d62 2023-10-27)
rustc 1.75.0-nightly (608e9682f 2023-10-29)
```

### Stack trace

```Shell
N/A
```

### Additional context

operator system: Linux From Scratch (Custom systems built from source code)

**Comment by HeavenVolkoff** [comment]
Did you run `pnpm prep` before compiling? It should have generated the files that are missing

**Comment by jack9603301** [comment]
Thanks, I may have forgotten, I'll give it a try - I recommend the community to use a separate document - such as BUILDING.md to describe the compilation process

**Comment by HeavenVolkoff** [comment]
The build steps are already included in the [CONTRIBUTING.md](https://github.com/spacedriveapp/spacedrive/blob/main/CONTRIBUTING.md#making-changes) file.

If you have any other problems building the project, feel free to comment here and I will re-open the issue.

**Comment by jack9603301** [comment]
![图片](https://github.com/spacedriveapp/spacedrive/assets/9047180/b98a0cea-ab56-4711-9f29-dcbf648b4fbc)
Could you improve the documentation so that users of possible unknown distributions (like me and other LFS users) can know exactly what system dependencies this program requires? To manually install system dependencies? You only need to add a special `Required Depends`

**Comment by jack9603301** [comment]
@HeavenVolkoff Can I ask what's going on?

![图片](https://github.com/spacedriveapp/spacedrive/assets/9047180/70aec162-2828-4c44-a3c2-8b832b8707fb)
What did i do wrong?

**Comment by HeavenVolkoff** [comment]
@jack9603301 how did you build the app? Did you run `pnpm tauri dev`/`pnpm tauri build` or did you use `cargo` directly? Because from the looks of that error message, it seems like you built the rust part but did not build the web frontend. Our wrapper command `pnpm tauri` takes care of this by building both the backend and frontend together.

**Comment by jack9603301** [comment]
> @jack9603301 how did you build the app? Did you run `pnpm tauri dev`/`pnpm tauri build` or did you use `cargo` directly? Because from the looks of that error message, it seems like you built the rust part but did not build the web frontend. Our wrapper command `pnpm tauri` takes care of this by building both the backend and frontend together.

I use the following command:

```
cargo build --release
```

What you mean is, I shouldn't use it directly to build, right?

**Comment by HeavenVolkoff** [comment]
I mean, you could use cargo directly, but then you would need to do the other steps manually. Build the front-end, copy the native libs, setup some pre- and post-build patches for doing releases builds, etc... which are not really documented anywhere beside the script itself that set those things up and some config files (mostly [here](https://github.com/spacedriveapp/spacedrive/blob/main/scripts/tauri.mjs), [here](https://github.com/spacedriveapp/spacedrive/blob/main/apps/desktop/src-tauri/tauri.conf.json) and [here](https://github.com/spacedriveapp/spacedrive/blob/main/apps/desktop/package.json)). So, my recommendation is to stick with the `pnpm tuari`  command to build the desktop app. For the server, you can use cargo directly from its [directory](https://github.com/spacedriveapp/spacedrive/tree/main/apps/server), as long as you have ran `./scripts/setup.sh` and `pnpm prep` before attempting to build it.

**Comment by jack9603301** [comment]
@HeavenVolkoff thanks

**Comment by DAOCUONG** [comment]
have same issue when run pnpm prep

Error[E0583]: file not found for module `prisma`
 --> crates/prisma/src/lib.rs:2:1
  |
2 | pub mod prisma;
  | ^^^^^^^^^^^^^^^
  |
  = help: to create the module `prisma`, create file "crates/prisma/src/prisma.rs" or "crates/prisma/src/prisma/mod.rs"

error[E0583]: file not found for module `prisma_sync`
 --> crates/prisma/src/lib.rs:4:1
  |
4 | pub mod prisma_sync;
  | ^^^^^^^^^^^^^^^^^^^^

**Comment by ParamBirje** [comment]
Hey @HeavenVolkoff,

Should the list of dependencies be under their own sub-heading categorized by their respective operating systems;
as given in the `setup.sh` and `setup.ps1` comments.

or

Should they be appended with the existing ones like [here](https://github.com/spacedriveapp/spacedrive/blob/7078bc05597ec2a6445cc13c8aa97f0773b05ee1/CONTRIBUTING.md?plain=1#L43).

**Comment by HeavenVolkoff** [comment]
@ParamBirje I think a list, like the one you linked, is best. A subheading can end up too long.

**Comment by ParamBirje** [comment]
After going through the install scripts, I have compiled the following list of dependencies that are common. 

Others that include build essentials, Tauri essentials and some specifics have been added as a link to the actual file. As including all of the packages may make the dependencies list in the CONTRIBUTING.md file spill over a couple of lines more. Though let me know what you think @HeavenVolkoff and if there's any changes needed.

```markdown
3. For Linux or MacOS users, run: `./scripts/setup.sh`
   - This will install Clang, NASM, LLVM, libvips, Gstreamer's Plugins, FFmpeg, Perl and any other [required dependencies](https://github.com/spacedriveapp/spacedrive/blob/main/scripts/setup.sh) for Spacedrive to build.
4. For Windows users, run the following command in PowerShell: `.\scripts\setup.ps1`
   - This will install pnpm, LLVM, FFmpeg, C++ build tools, NASM, Rust + Cargo, Rust tools, Edge Webview 2, Strawberry Perl and any other [required dependencies](https://github.com/spacedriveapp/spacedrive/blob/main/scripts/setup.ps1) for Spacedrive to build.
```

**Comment by HeavenVolkoff** [comment]
@ParamBirje If we are listing the dependencies for each system, it would be better to split macOS and Linux into their own entries. Also, to avoid having to list all the dependencies individually we could just link to tauri's setup docs, as the majority of the dependencies we are installing are just for tauri:
https://tauri.app/v1/guides/getting-started/prerequisites/#setting-up-windows
https://tauri.app/v1/guides/getting-started/prerequisites/#setting-up-macos
https://tauri.app/v1/guides/getting-started/prerequisites/#setting-up-linux

**Comment by ParamBirje** [comment]
Hey @HeavenVolkoff,
Here's the updated list with each system as a separate entry to make traversing through the requirements more easily accessible. Let me know if any changes are needed on this


3. For Linux users, run: `./scripts/setup.sh`
   - This will install Clang, NASM, LLVM, libvips, Gstreamer's Plugins, FFmpeg, Perl, [Tauri essentials](https://tauri.app/v1/guides/getting-started/prerequisites/#setting-up-linux) and any other required dependencies for Spacedrive to build.
4. For MacOS users, run: `./scripts/setup.sh`
   - This will check if Xcode is installed, use Homebrew to install NASM, Rust Targets for iOS, [Tauri essentials](https://tauri.app/v1/guides/getting-started/prerequisites/#setting-up-macos) and install any other required dependencies for Spacedrive to build.
5. For Windows users, run the following command in PowerShell: `.\scripts\setup.ps1`
   - This will install pnpm, LLVM, FFmpeg, C++ build tools, NASM, Rust + Cargo, Rust tools, Edge Webview 2, Strawberry Perl, [Tauri essentials](https://tauri.app/v1/guides/getting-started/prerequisites/#setting-up-windows) and any other required dependencies for Spacedrive to build.

**Comment by HeavenVolkoff** [comment]
@ParamBirje Yeah better to link each OS to their respective setup script, so the user can check what we are running directly from the docs if he wishes.
Linux:  https://github.com/spacedriveapp/spacedrive/blob/main/scripts/setup.sh#L133
macOS: https://github.com/spacedriveapp/spacedrive/blob/main/scripts/setup.sh#L108
Windows: https://github.com/spacedriveapp/spacedrive/blob/main/scripts/setup.ps1#L81

macOS setup script only installs the iOS rust targets when the user passes the `mobile` argument to it, so I don't think they should be listed in the dependencies. Also, it would be good to add to macOS and Linux entries that the script will check if Rust and pnpm are already installed

Btw, feel free to open a PR with your changes
