### ISSUE TITLE
PDF preview not working in appimage version

### ISSUE THREAD

**Issue by joezhouchenye** [spacedriveapp/spacedrive#1807]
### Describe the bug

Cannot preview pdf in appimage version.

![image](https://github.com/spacedriveapp/spacedrive/assets/59191277/8d6541e9-1766-40ca-8fce-441e780538e9)

.deb version is tested and it has no such problem

### Platform and versions

```Shell
Ubuntu 22.04
appimage version 0.1.2
```

**Comment by HeavenVolkoff** [comment]
Hello, I am currently reworking the `appimage` for Spacedrive in #1785. As soon as I have a working build of the new appimage I will test to see if this issue still occurs or not
