### ISSUE TITLE
PDF thumbnails are inverted

### ISSUE THREAD

**Issue by ShahriarKh** [spacedriveapp/spacedrive#1816]
### Describe the bug

Thumbnails generated for PDFs are inverted.

## Space Drive (incorrect):
![image](https://github.com/spacedriveapp/spacedrive/assets/31452340/560a0d1e-6095-454f-8034-cceaf14f15bd)

## Windows Explorer (correct):
![image](https://github.com/spacedriveapp/spacedrive/assets/31452340/f102e059-c2d5-47bb-b671-c0fed3d55930)

### Reproduction

1. Go to a folder containing pdf files
2. Wait for thumbnails to be generated

### Expected behavior

The thumbnails should show in correct color

### Platform and versions

```Shell
+ v0.1.3 - e3c2c90
+ cargo 1.74.0 (ecb9851af 2023-10-18)
+ rustc 1.74.0 (79e9716c9 2023-11-13)
+ Windows 10 - 22H2 (19045.3570)
```

**Comment by brxken128** [comment]
#1815 should fix this.

**Comment by ShahriarKh** [comment]
> This might actually be due to the fact that our PDF renderer disables annotations and other stuff, may be worth re-enabling but I'm not sure why they're disabled in the first place

But when I open the pdf in quick view, it shows correctly; so I guess it's not related to that (maybe?)
![image](https://github.com/spacedriveapp/spacedrive/assets/31452340/97586df7-5b4d-497a-9691-397e03e1cdc9)

I also tried setting Thumbnailer CPU Usage to max and Regen Thumbnails but no luck.

**Comment by brxken128** [comment]
> > This might actually be due to the fact that our PDF renderer disables annotations and other stuff, may be worth re-enabling but I'm not sure why they're disabled in the first place
> 
> But when I open the pdf in quick view, it shows correctly; so I guess it's not related to that (maybe?)
> ![image](https://github.com/spacedriveapp/spacedrive/assets/31452340/97586df7-5b4d-497a-9691-397e03e1cdc9)
> 
> I also tried setting Thumbnailer CPU Usage to max and Regen Thumbnails but no luck.
> 

The quick preview actually sources and shows the file itself, adjusting how many threads the thumbnailer scales to won't affect the outcome of the thumbnail - it's something to do with the PDF rendering config most likely.

**Comment by HeavenVolkoff** [comment]
Hey @ShahriarKh does Chrome/Chromium render both of these PDFs correctly? (We are using the same lib as Chrome to render PDFs). Also, could you maybe share these file so we could test them? (If you can't that is ok). Are these the only PDFs that you observed this behavior, or all of your PDFs are inverted?

**Comment by HeavenVolkoff** [comment]
Found an example PDF that reproduce this:
![image](https://github.com/spacedriveapp/spacedrive/assets/9082460/aae7f38f-ef3e-40ca-a3d2-9254290e7653)

Left is original, right is our thumbnail. This seems like a case of BGR being interpreted as RGB, considering blue and red are being inverted, but green remains the same

**Comment by ShahriarKh** [comment]
I updated to 0.1.4 but the issue is still there 👀 (Tried regen and even reindex)
@HeavenVolkoff It's not a specific file; I have around 400 pdfs in different locations and all of them are affected by this.

**Comment by HeavenVolkoff** [comment]
@ShahriarKh could you try, with the app closed, going to `%appdata%\spacedrive` (in explorer) and deleting the thumbnails folders. Then, check again if the thumbnails still have issue. Because 0.1.4 does include my fix and so far all the PDFs I tested with, that had inverted colors, generated correct thumbnails after this fix. Maybe the thumbnail regen is broken.

**Comment by ShahriarKh** [comment]
Deleting the folder worked! Thanks.
