### ISSUE TITLE
Hide or show empty state for tag search filter if there are no tags

### ISSUE THREAD

**Issue by PineappleRind** [spacedriveapp/spacedrive#1858]
### Describe the bug

<img width="401" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/65303441/d2a6305a-b42a-4ea8-b225-51fa46927b76">

If there are no tags, this option should show an empty state (or maybe even hide it completely?)

### Platform and versions

```Shell
Spacedrive v0.1.4 (2f01b21)
```

**Comment by ameer2468** [comment]
This will be addressed - thank you for the report.
