### ISSUE TITLE
MOUSE4 and MOUSE5 (back/forward) not working on Linux (AppImage)

### ISSUE THREAD

**Issue by benterova** [spacedriveapp/spacedrive#1876]
### Describe the bug

When navigating through directories and attempting to go back via MOUSE4, or forward via MOUSE5, nothing happens. It appears both of these button presses are currently treated as MOUSE1, as dragging while pressed selects a region, deselects with a selected item and clicked in a blank area, and can be double pressed to open a file/folder.

### Reproduction

Open any directory
Try to go back to the previous directory via Mouse4
Input is treated as mouse1 instead of back.

### Expected behavior

Mouse4 should navigate backwards, and mouse 5 should navigate forwards.

### Platform and versions

```Shell
# System Details Report
---

## Report details
- **Date generated:**                              2023-12-07 11:58:00

## Hardware Information:
- **Hardware Model:**                              Micro-Star International Co., Ltd. MS-7D77
- **Memory:**                                      64.0 GiB
- **Processor:**                                   AMD Ryzen™ 7 7800X3D × 16
- **Graphics:**                                    AMD Radeon™ RX 6800
- **Graphics 1:**                                  AMD Radeon™ Graphics
- **Disk Capacity:**                               2.0 TB

## Software Information:
- **Firmware Version:**                            1.90
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.2
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.4-cb1.0.fc39.x86_64


SpaceDrive v0.1.4
```

### Stack trace

```Shell
None
```

### Additional context

This is using the AppImage build of the application.

**Comment by ameer2468** [comment]
Hey thanks for the report! For Linux support we are awaiting a new release by Tauri, version 2. This will help us to potentially provide support for Linux. We'll keep this noted and will keep everyone updated :)

**Comment by utkubakir** [comment]
Tracked on #1957
