### ISSUE TITLE
nixos appimage install fails

### ISSUE THREAD

**Issue by dougkeiller** [spacedriveapp/spacedrive#1881]
### Describe the bug

when I try to install the appimage on nixos using the official nixos instructions, I get an error described below

### Reproduction

[nix-shell:~/Downloads]$ appimage-run Spacedrive-linux-x86_64.AppImageSpacedrive-linux-x86_64.

AppImage installed in /home/doug/.cache/appimage-run/881756f223eebf3b4fd0be712f256ceff2bcc857bb903ed0c1d4ee2892e107e7

spacedrive: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory

### Expected behavior

install spacedrive

### Platform and versions

```Shell
[nix-shell:~/Downloads]$ pnpm --version && cargo --version && rustc --version
8.12.0
cargo 1.74.1 (ecb9851af 2023-10-18)
rustc 1.74.1 (a28077b28 2023-12-04)

Nixos 23.11
```

**Comment by yretenai** [comment]
Same issue happens on Gentoo.
