### ISSUE TITLE
Library selector has focus ring on initial render

### ISSUE THREAD

**Issue by maxichrome** [spacedriveapp/spacedrive#191]
On the app's initial render, the library chooser is focused by default and displays a visible focus ring. (See screenshot)

<img width="312" alt="A screenshot of the very top-left corner of the macOS app. There is a dropdown with a light purple outline around it indicating that it currently has keyboard focus." src="https://user-images.githubusercontent.com/33473181/171072428-9452b304-26d7-4026-b758-94d824ad9866.png">

## Reproduction

1. Open the desktop app (in my case using `pnpm desktop dev`)
2. Look for the focus ring on the library chooser

## Expected behavior

- No element should initially have visible focus.
- Unless determined otherwise, pressing <kbd>Tab</kbd> should apply focus to the library chooser as it's the first visible onscreen element.

## Platform and versions

Commit: f193f45
OS: macOS Monterey version 12.4 (21F79)
Safari: Version 15.5 (17613.2.7.1.8)

```
❯ pnpm --version && cargo --version && rustc --version
7.1.5
cargo 1.60.0 (d1fd9fe2c 2022-03-01)
rustc 1.60.0 (7737e0b5c 2022-04-04)
```

**Comment by Looskie** [comment]
Hi, could you provide more infor??
