### ISSUE TITLE
when searching

### ISSUE THREAD

**Issue by JonZhang3** [spacedriveapp/spacedrive#1910]
### Describe the bug

<img width="375" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/53330083/e09a411e-aeee-447e-9a7d-9a69dff8c7d4">

### Platform and versions

```Shell
8.13.1
cargo 1.74.0 (ecb9851af 2023-10-18)
rustc 1.74.0 (79e9716c9 2023-11-13)

macos 14.2(M1)
```

**Comment by 0xBA5E64** [comment]
The lack of information in this ticket makes it hard to judge, but if I were to guess from the screenshot, it's about the window title showing up on MacOS while the search-field is focused, which I believe was fixed in https://github.com/spacedriveapp/spacedrive/pull/1936

**Comment by utkubakir** [comment]
Yup this is fixed.
