### ISSUE TITLE
[Linux, AppImage, X11] Black Screen on launch v0.2

### ISSUE THREAD

**Issue by newyorkthink** [spacedriveapp/spacedrive#1993]
### Describe the bug

always black show, cannot run the latest version

https://github.com/spacedriveapp/spacedrive/assets/87791643/fad5b498-6c5a-4160-8ed1-7042ace0a54b

### Platform and versions

```Shell
appimage
debian
i3wm env
spacedrive version is :0.2.0
```

**Comment by HeavenVolkoff** [comment]
@newyorkthink can you reproduce the same problem with the `.deb` version?

**Comment by HeavenVolkoff** [comment]
This issue is very likely to be the same as #2039. Closing this, because all the discussion for finding the cause happened there.
