### ISSUE TITLE
Unable to Install on Windows

### ISSUE THREAD

**Issue by astridos2go** [spacedriveapp/spacedrive#1994]
### Describe the bug

When I attempt to install Spacedrive on my Windows 11 PC, I get an error message saying 
> There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.

![image](https://github.com/spacedriveapp/spacedrive/assets/45048997/e304c557-b553-4354-8bd6-6c7ea990d64a)

### Reproduction

- Download the latest installer (Alpha 0.2.0) as the `msi`. 
- Click to run it. 
- It fails

### Expected behavior

- Download the latest installer
- Click to run it
- It succeeds 😄 

### Platform and versions

```Shell
# Output of `pnpm --version && cargo --version && rustc --version`

8.14.3
cargo 1.75.0 (1d8b05cdd 2023-11-20)
rustc 1.75.0 (82e1608df 2023-12-21)

# OS Information
OS Name: Microsoft Windows 11 Pro
Version: 10.0.22631 Build 22631
```

### Stack trace

```Shell
I'm not sure where to get this...
```

**Comment by i0x0** [comment]
Having the same issue here but using a modified Windows 10 PC

**Comment by artsiom-voitas** [comment]
Same issue on Windows 11 Pro 23H2

**Comment by candroid-man** [comment]
Same here

**Comment by davidjaggi** [comment]
I have the same problem.

**Comment by HeavenVolkoff** [comment]
Sorry about this, I'm not entirely sure why this issue is happening, and none of the team members were able to reproduce the installation problem. However, thanks to the logs provided by @isilweo, I believe I've identified the cause. I'm currently building a test release with a potential fix [here](https://github.com/spacedriveapp/spacedrive/actions/runs/7677844014). If possible, could anyone who was affected by this issue try installing the test release and check if it works correctly and report back. Thanks

**Comment by isilweo** [comment]
It works correctly now thanks :)

one side note - to generate log from installer you need to run it from command line like installer.exe /log file.txt - be aware that there may be private data in log like email and computer username etc, so take a look before posting.

**Comment by i0x0** [comment]
It works correctly now 👍🏿

**Comment by JRBlaze** [comment]
> Sorry about this, I'm not entirely sure why this issue is happening, and none of the team members were able to reproduce the installation problem. However, thanks to the logs provided by @isilweo, I believe I've identified the cause. I'm currently building a test release with a potential fix [here](https://github.com/spacedriveapp/spacedrive/actions/runs/7677844014). If possible, could anyone who was affected by this issue try installing the test release and check if it works correctly and report back. Thanks

This fix worked for me.

**Comment by v-Kaefer** [comment]
Couldn't test it yet in VMs, but is this expected?

![Screenshot_22](https://github.com/spacedriveapp/spacedrive/assets/128633407/9569c4d4-66d2-427c-87f1-5562aeb13034)

**Comment by brxken128** [comment]
> Couldn't test it yet in VMs, but is this expected?
> 
> ![Screenshot_22](https://github.com/spacedriveapp/spacedrive/assets/128633407/9569c4d4-66d2-427c-87f1-5562aeb13034)
> 

Yes, it happens as SmartScreen is usually not trusting of a binary until enough users run it and don't have any complaints - this is often when we release a new update, but after a few days/a week Microsoft unofficially consider it as "likely safe", and dismiss the warning for that specific binary/executable.

It can be resolved through signing too, but I'm not too sure if we have that configured for Windows or not (we had some issues with obtaining a key previously)?.

**Comment by HeavenVolkoff** [comment]
> Couldn't test it yet in VMs, but is this expected?

You got this with the 0.2 release or with my test release? I've been sending our releases `.exe` to be scanned by MS to avoid this, but I didn't with the test release, so if you got this by running it, it was expected.

**Comment by brxken128** [comment]
> > Couldn't test it yet in VMs, but is this expected?
> 
> You got this with the 0.2 release or with my test release? I've been sending our releases `.exe` to be scanned by MS to avoid this, but I didn't with the test release, so if you got this by running it, it was expected.

I got it with the latest 0.2.0 release last I checked

**Comment by v-Kaefer** [comment]
> > Couldn't test it yet in VMs, but is this expected?
> 
> You got this with the 0.2 release or with my test release? I've been sending our releases `.exe` to be scanned by MS to avoid this, but I didn't with the test release, so if you got this by running it, it was expected.

Actually, both.

**Comment by v-Kaefer** [comment]
> Yes, it happens as SmartScreen is usually not trusting of a binary until enough users run it and don't have any complaints - this is often when we release a new update, but after a few days/a week Microsoft unofficially consider it as "likely safe", and dismiss the warning for that specific binary/executable.
> 
> It can be resolved through signing too, but I'm not too sure if we have that configured for Windows or not (we had some issues with obtaining a key previously) and can't remember what happened afterwards from the top of my head.

Okay, now i got it installed, just fine with @HeavenVolkoff version.
Because, with the official release version 0.2.0, it would crash at the end, as reported by the other users.
![Screenshot_27](https://github.com/spacedriveapp/spacedrive/assets/128633407/4925bb85-0048-4531-bbc7-334623fdb762)
![Screenshot_28](https://github.com/spacedriveapp/spacedrive/assets/128633407/25a52ef7-357e-439f-8778-7f2699f4c68c)

**Comment by astridos2go** [comment]
> Sorry about this, I'm not entirely sure why this issue is happening, and none of the team members were able to reproduce the installation problem. However, thanks to the logs provided by @isilweo, I believe I've identified the cause. I'm currently building a test release with a potential fix [here](https://github.com/spacedriveapp/spacedrive/actions/runs/7677844014). If possible, could anyone who was affected by this issue try installing the test release and check if it works correctly and report back. Thanks

This test installer worked perfectly for me!
