### ISSUE TITLE
Folders are indexed as type 'Unknown'

### ISSUE THREAD

**Issue by TwanLuttik** [spacedriveapp/spacedrive#2005]
### Describe the bug

Adding a location sets its type to `Unkown`

![CleanShot 2024-01-27 at 12 34 26@2x](https://github.com/spacedriveapp/spacedrive/assets/19343894/cafe88e7-62ab-463c-bc5f-d20f38740dac)

and of course the search with the folder type will be effected at that point.

![CleanShot 2024-01-27 at 12 34 38@2x](https://github.com/spacedriveapp/spacedrive/assets/19343894/031bde27-8197-4ae8-8093-ee97de858acc)

### Platform and versions

```Shell
v0.2.0
```

**Comment by iLynxcat** [comment]
hey Twan, is this happening on v0.4.0 still?

**Comment by TwanLuttik** [comment]
This is working and closing the issue now
