### ISSUE TITLE
Copy from non indexed to a indexed location no work

### ISSUE THREAD

**Issue by TwanLuttik** [spacedriveapp/spacedrive#2026]
### Describe the bug

- You cannot copy & paste from a indexed to a non indexed location
- You cannot copy & paste from a non indexed location to a indexed and non-indexed location

So basically you can only copy from indexed location to indexed location and i think every direction should be allowed in this case?

(video desc: copy from non indexed to indexed location).

https://github.com/spacedriveapp/spacedrive/assets/19343894/391a6af1-d26f-40f5-8e85-3beacbdcb412

### Platform and versions

```Shell
v0.2.2
```

**Comment by niikeec** [comment]
Thanks for the report. What you can do in the meantime is drag and drop, which works in all directions non-indexed -> indexed and indexed -> non-indexed
