### ISSUE TITLE
Chinese language cannot be displayed

### ISSUE THREAD

**Issue by lvzhenbo** [spacedriveapp/spacedrive#2047]
### Describe the bug

Very happy to add multi-language support, but Chinese doesn't seem to be able to be displayed, whether you choose Simplified Chinese or Traditional Chinese it's all in English!
![image](https://github.com/spacedriveapp/spacedrive/assets/32427677/34535b39-7316-49fc-9d0e-74349b656ace)

### Reproduction

1. Set to Chinese language environment
2. Select Chinese language in the program

### Expected behavior

Ability to demonstrate Chinese

### Platform and versions

```Shell
OS: Windows 11 Professional 23H2 22631.3085

Program Version: 0.2.3

Edge WebView2: 121.0.2277.98
```

**Comment by utkubakir** [comment]
Can confirm, will fix it soon
