### ISSUE TITLE
Confusing app icon

### ISSUE THREAD

**Issue by berkus** [spacedriveapp/spacedrive#2064]
### Describe the bug

<img width="162" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/80306/523230fc-0c68-4c83-8aa7-226b500352ae">

Can you guess at first sight which is which?

### Reproduction

1. Install Spacedrive
2. Install OrbStack
3. Launch both

### Expected behavior

Have a distinctive icon that lets you find the app without tediously scrolling through all similar icons (I have three almost identical icons for email client, terminal and note taking app, now there's also two almost similar icons for Spacedrive and OrbStack, the trend is frightening).

### Platform and versions

```Shell
pnpm --version && cargo --version && rustc --version
fish: Unknown command: pnpm
cargo 1.76.0-nightly (9b13310ca 2023-11-24)
rustc 1.76.0-nightly (49b3924bd 2023-11-27)

Definitely this has great effect on the icon:

macOS Sonoma 14.0
```

**Comment by utkubakir** [comment]
I mean, you could ask them if you really like. We were first and not planning on changing anything as we really (as a team) don't care.

**Comment by jamiepine** [comment]
Not only were we first but our overlap in demographic is minimal anyway. Funny issue though.
