### ISSUE TITLE
Video thumbnails have streaks or rapid zoom jitter

### ISSUE THREAD

**Issue by JasonLamv-t** [spacedriveapp/spacedrive#2150]
### Describe the bug

![image](https://github.com/spacedriveapp/spacedrive/assets/39087996/f6b7c50e-e7eb-4366-b622-0df4db19656a)
![Kapture 2024-02-29 at 16 46 27](https://github.com/spacedriveapp/spacedrive/assets/39087996/6f9fd356-2568-4a96-8fae-0c9eb1123469)

As the title and the pic.

### Reproduction

1. Open the software
2. Click the Video category shown on the top of the main page

### Platform and versions

```Shell
pnpm --version && cargo --version && rustc --version
8.15.4
cargo 1.76.0 (c84b36747 2024-01-18)
rustc 1.76.0 (07dca489a 2024-02-04)
```

**Comment by niikeec** [comment]
I can't reproduce the issue. Are you on the latest version?

**Comment by JasonLamv-t** [comment]
> I can't reproduce the issue. Are you on the latest version?

<img width="300" alt="image" src="https://github.com/spacedriveapp/spacedrive/assets/39087996/41d0468d-6c2b-4e31-b56b-1fe8f047d487">

**Comment by niikeec** [comment]
Thank you, was able to reproduce it.

**Comment by JasonLamv-t** [comment]
@brxken128, Thank you for your reply.
I notice that the encoding of most problematic videos is MP4, and most of these videos were shot a few years ago so I can't make sure that the problem was caused by the video itself. I also noticed that most of their size are very small and seem likely shot in WeChat, a social app in mainland China, which will zip the video.
I already upload two videos (check [here](https://github.com/JasonLamv-t/datalake/tree/main/spacedrive)). I believe these videos were shot within a similar period, but I can't confirm the source.

**Comment by brxken128** [comment]
@JasonLamv-t The broken video appears to be using H264, which is the most common encoding type that our app deals with - I'm unsure as to why it's broken.

I'll load these videos into a local build of Spacedrive and see the results.

In the meantime, please could you try right clicking in the explorer, hitting "more actions" and then "regen thumbnails" to see if regenerating them fixes the issue? Thank you!

**Comment by JasonLamv-t** [comment]
@brxken128 Sorry about that I can't find the "more actions" option that you mentioned above. Can you give me a screenshot for a demo?

**Comment by MusaSSH** [comment]
I noticed that this problem is occuring only on vertical videos, horizontal is fine. Those two videos are recorded by my mobile phone, they're H264 and I assume they're encoded with the same encode settings.

![resim](https://github.com/spacedriveapp/spacedrive/assets/97892949/fdfd1e8e-d276-49a3-85fa-ab05d49b1df8)

**Comment by HeavenVolkoff** [comment]
This is probably some minor issue in the [movie_decoder](https://github.com/spacedriveapp/spacedrive/blob/main/crates/ffmpeg/src/movie_decoder.rs) logic, I am currently [making changes to this part of the code base](https://github.com/spacedriveapp/spacedrive/pull/2285), will try taking a look for why this is not working properly
