### ISSUE TITLE
Wacatac.B!ml detected after downloading installer

### ISSUE THREAD

**Issue by adrianratajczak** [spacedriveapp/spacedrive#2176]
### Describe the bug

Hi, Windows Defender reported a Wacatac.B!ml detection when trying to run the installer. 
I haven't found any information about Wacatac.B!ml in the case of spacedrive so I'd like to know more

### Platform and versions

```Shell
Windows 11
```

**Comment by brxken128** [comment]
This is a false positive, I believe it's caused by Prisma or something similar but I can't quite remember off the top of my head.
