### ISSUE TITLE
the prebuild installers for windows are all broken

### ISSUE THREAD

**Issue by rubenh2905** [spacedriveapp/spacedrive#2180]
### Describe the bug

i literally downloaded this all 3 times (1. from the website 2/3. both availble versions in the github tag 0.2.5) and non of them worked
when i'm trying to open the Spacedrive.exe it will run for a split of second and then terminate with no logs errors and nothing that says what is going on

### Platform and versions

```Shell
windows 10
last time i tryed to build it from source it did not worked at all (not even on the docker) so i did not tryed to build from source this time, just downloaded the prebuild msi files
```

**Comment by artsiom-voitas** [comment]
try to delete this folder C:\Users\"User Name"\AppData\Roaming\spacedrive

**Comment by HeavenVolkoff** [comment]
Hi, is this still happening with the latest release?

**Comment by HeavenVolkoff** [comment]
Closing this. Fell free to open a new issue if this problem persists with the latest release
