### ISSUE TITLE
Crashes, wont reopen Sonoma 14.2.1

### ISSUE THREAD

**Issue by m0rg5** [spacedriveapp/spacedrive#2182]
### Describe the bug

Not sure what else to tell you, prior version crashed on opening after adding dir. Just downloaded, instaleld alpha 2.5, does not open.

### Reproduction

Doesn't open.

### Platform and versions

```Shell
Sonoma 4.2.1
```

**Comment by brxken128** [comment]
Can you try running `rm -rf "~/Library/Application Support/spacedrive` and try again please?

**Comment by m0rg5** [comment]
Added " , no change, hangs "application not responding", have to force quit.

**Comment by zhengpd** [comment]
`rm -rf "~/Library/Application Support/com.spacedrive.desktop/"` gives me a fresh start of spacedrive without previous settings.

**Comment by zhengpd** [comment]
Won't reopen again. 

Apple M1, Sonoma 14.4.1

**Comment by m0rg5** [comment]
Updated to 0.2.8 and it opened, then froze when opening (spacebar) a PDF. Can access menu but nothing else responds.

**Comment by utkubakir** [comment]
@m0rg5 how are things on the last version?

**Comment by m0rg5** [comment]
Can open, seems ok so far 👍
