### ISSUE TITLE
v0.2.5 Cannot enable networking on Windows

### ISSUE THREAD

**Issue by greatbody** [spacedriveapp/spacedrive#2200]
### Describe the bug

I am using Windows 11
v0.2.5 spacedrive cannot enable networking on windows.

### Reproduction

![image](https://github.com/spacedriveapp/spacedrive/assets/6984599/e5a43cac-ddda-4f8a-b364-7ef041ddb0d1)

### Expected behavior

Can click to toggle on network, and be able to see my macOS with Spacedrive installed.

### Platform and versions

```Shell
Windows 11 Professional
```

**Comment by niikeec** [comment]
The switch is currently disabled

**Comment by greatbody** [comment]
> The switch is currently disabled

Thanks for sharing the context.

Why we disable that switch for Windows?

**Comment by niikeec** [comment]
It is currently disabled on all platforms, tho we should have communicated this in a better way, as it can confuse users.

**Comment by utkubakir** [comment]
Sync & spacedrop are heavily "work in progress" right now which is why it's disabled

**Comment by greatbody** [comment]
> Networking is still "work in progress" which is why it's disabled

Do we have a road map for network function?

**Comment by utkubakir** [comment]
> Do we have a road map for network function?

@oscartbeaumont added the functionality and added the button back on #2365 :)

**Comment by oscartbeaumont** [comment]
The button got broken during some big internal networking changes hence it getting disabled in the UI but i'm bringing it back now cause I fixed it.

As of right now Spacedrop is the only networked functionality within the app that has publically launched.

Most of the other networked functionality is probably going to launch alongside sync. Most of it's within the app and we are working on making it more reliable and seamless.
