### ISSUE TITLE
can not switch to chinese real-time

### ISSUE THREAD

**Issue by HeavySnowJakarta** [spacedriveapp/spacedrive#2242]
### Describe the bug

When switch to chinese (simplified and traditional) it does not work immediately but changes to english. Only after restarting it works.

Not for all other languages including Japanese.

### Platform and versions

```Shell
release 0.2.6 for Windows

Windows 11 22H2
```

**Comment by utkubakir** [comment]
This is fixed and will be available on the next patch (will come out today)
