### ISSUE TITLE
Display east Asain characters

### ISSUE THREAD

**Issue by HeavySnowJakarta** [spacedriveapp/spacedrive#2243]
### Describe the bug

![图片](https://github.com/spacedriveapp/spacedrive/assets/54460050/fc19da5e-39d6-4adf-b511-9711b19126c0)

As the image shows the button "export" is displayed vertically. There is nothing wrong to display east Asain characters vertically but we usually just show them horizontally and the case of the image is actually weird. Try to adjust the width to contain the characters into one line.

The same problem exists for Japanese.

### Platform and versions

```Shell
release 0.2.6 for Windows

Windows 11 22H2
```

**Comment by HeavySnowJakarta** [comment]
still not working @niikeec

**Comment by HeavySnowJakarta** [comment]
![图片](https://github.com/spacedriveapp/spacedrive/assets/54460050/b09f4e25-797b-4240-8168-1e0918780c50)

**Comment by niikeec** [comment]
The fix will be included in the next version
