### ISSUE TITLE
[ENG-293] Tag assign mode

### ISSUE THREAD

**Issue by jamiepine** [spacedriveapp/spacedrive#2350]
This feature makes assigning tags extremely simple and will be a prominent feature in the marketing material.

The tag button in the TopBar should hide the path view and instead show a line up of numbered tags, selecting some files and pressing that number will assign a tag to those files.

Another approach to this could be to have a floating tag picker UI that works in a similar fashion as above.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-293](https://linear.app/spacedriveapp/issue/ENG-293/tag-assign-mode)</sub>

**Comment by iLynxcat** [comment]
Accidentally auto-completed this when resolving some problems with GitHub. reopening as this is still WIP
