### ISSUE TITLE
[ENG-1393] Keyboard file navigation

### ISSUE THREAD

**Issue by utkubakir** [spacedriveapp/spacedrive#2359]
> I'm really excited for this project, and I think this would make it much quicker to use. So, for most file browsers on Linux (although I'm sure others support it), while focusing the window, you have the ability to just start typing and the file explorer will highlight files for you that match what you have typed.
>
> I know there is a search feature, but this would more match immediate files in a directory with no fuzzy search.
>
> Additionally, if you type '/' or '\~', most file explorers take you to the root and home directory and allow you type a full path after those key characters. I think this would be a great feature to add as well, as these are very common directories. I don't know how other systems would interact with this (such as android, windows, or ios), but maybe they could do something similar. I also am unsure of how this would work with having multiple root directories (multiple machines with space drive), but maybe it could just be localized to that machine once selected or something.

^^ This is from a github discussion, I believe we already talked this on Slack, great feature we need to work on!

Another:

![image.png](https://uploads.linear.app/acbbe821-841d-473d-bf38-d1d995f656fb/75af830c-1917-4d1a-a7f5-ddb55dd29219/00b43eb9-2f96-4c3a-afdf-c65d58ac41a8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjYmJlODIxLTg0MWQtNDczZC1iZjM4LWQxZDk5NWY2NTZmYi83NWFmODMwYy0xOTE3LTRkMWEtYTdmNS1kZGI1NWRkMjkyMTkvMDBiNDNlYjktMmY5Ni00YzNhLWFmZGYtYzY1ZDU4YWM0MWE4IiwiaWF0IjoxNzEzNDkzMzE3LCJleHAiOjE3MTM1Nzk3MTd9.HYx10y8Mj1O1e-LHkZtAJOsKfPLVWrF8gFZNzqCvGpM)

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-1393](https://linear.app/spacedriveapp/issue/ENG-1393/keyboard-file-navigation)</sub>

**Comment by iLynxcat** [comment]
Closing this to merge into #2705
