### ISSUE TITLE
Has no file

### ISSUE THREAD

**Issue by ncwuguo** [spacedriveapp/spacedrive#2388]
### Describe the bug

It's show none in my disk c, disk d and e is also has no file.
![image](https://github.com/spacedriveapp/spacedrive/assets/54211354/d5266fa2-eac9-40c9-99bb-38a2fae7ce79)

### Platform and versions

```Shell
windows 11 23H2
V0.2.12
```

**Comment by utkubakir** [comment]
Can confirm the bug, we are working on it

**Comment by fogodev** [comment]
I think it should've been fixed with https://github.com/spacedriveapp/spacedrive/pull/2399. Can you check again?

**Comment by ncwuguo** [comment]
> I think it should've been fixed with #2399. Can you check again?

It's OK now in v0.2.14-952bb2d.
