### ISSUE TITLE
Renaming location causes re-index

### ISSUE THREAD

**Issue by TwanLuttik** [spacedriveapp/spacedrive#2397]
### Describe the bug

After you added a location, you change the name of the location through the settings and it seems its re indexing the location again.
 
i renamed to `Coatcheck` to `Coatcheck codebase`
![CleanShot 2024-04-25 at 12 27 57@2x](https://github.com/spacedriveapp/spacedrive/assets/19343894/78aa6cb8-d424-404c-903a-b5ff43104899)

### Platform and versions

```Shell
spacedrive - v0.2.12
```

**Comment by iLynxcat** [comment]
@matheus-consoli when you have time will you update tags on this issue?

**Comment by matheus-consoli** [comment]
Hi @TwanLuttik

Sorry for taking so long to answer here. I tried reproducing the issue, but it worked as expected - I think we have fixed it in the meantime. Can you confirm if this is still an issue for you, please?

**Comment by matheus-consoli** [comment]
closing this as fixed :) please reopen if you reencounter this issue or if it is still not fixed for you
