### ISSUE TITLE
Formatting dates with i18n

### ISSUE THREAD

**Issue by artsiom-voitas** [spacedriveapp/spacedrive#2406]
### Describe the bug

Currently, Spacedrive formats dates, for example on (spacedrive\interface\app$libraryId\Explorer\Inspector\index.tsx):
`<MetaData icon={Eraser} label={t('modified')} value={formatDate(dateModified)} />`
using JavaScript capabilities, which makes it impossible to have date mapping in different languages. 
It is worth considering using the i18n functions provided in the [documentation](https://www.i18next.com/translation-function/formatting#datetime)

### Reproduction

1. Check date in Inspector

### Expected behavior

Date formatting matches app language.

### Platform and versions

```Shell
spacedrive - v0.2.13
```

**Comment by utkubakir** [comment]
We should tackle this https://github.com/spacedriveapp/spacedrive/discussions/2389 with this issue also

**Comment by artsiom-voitas** [comment]
> We should tackle this https://github.com/spacedriveapp/spacedrive/discussions/2389 with this issue also

Do you want to add Date Format selector in the settings? Somewhere under Language settings? If yes, I will continue work on this matter tomorrow, if you want to format according to language preferences, I can push it now

**Comment by utkubakir** [comment]
> Do you want to add Date Format selector in the settings? Somewhere under Language settings? If yes, I will continue work on this matter tomorrow, if you want to format according to language preferences, I can push it now

Yes, I think we should default to the local time settings and user should also be able to change it

**Comment by artsiom-voitas** [comment]
> > Do you want to add Date Format selector in the settings? Somewhere under Language settings? If yes, I will continue work on this matter tomorrow, if you want to format according to language preferences, I can push it now
> 
> Yes, I think we should default to the local time settings and user should also be able to change it

Is it good idea to make a changes to local time from chosen language? For example, We add two version of English:
1. English (US): which will match key en_US and bring us MM/DD/Year and 12 hours formatting
2. English (UK): which will math key en_UK and bring us DD/MM/Year and 24 hours formatting
Also, we will have a feature in settings to change preferable date formatting style, from the list
![image](https://github.com/spacedriveapp/spacedrive/assets/85301789/6514491a-e5e6-4fff-a36b-1d2f52192f45)
Does It sound correct?

**Comment by utkubakir** [comment]
yup, options like "System", "DD/MM/YYYY", "M/D/Y" would be nice. And for extra points, we could display how it would look under the time display setting so it's easily understandable.
