### ISSUE TITLE
[docs]: links to changelog are broken

### ISSUE THREAD

**Issue by zaaakher** [spacedriveapp/spacedrive#2416]
### Describe the bug

When clicking on the "changelog" in the footer of the landing site it goes to a next.js error 500
When clicking on the "changelog" in the sidebar of the docs site it also goes to a next.js error 500

When I type https://www.spacedrive.com/docs/changelog/alpha/0.2.13 in the browser it goes to error 500. If I make the version 0.2.12 it also goes to error 500.

If I type https://www.spacedrive.com/docs/changelog/alpha/0.2.11 then it works fine. And I can then switch to 0.2.12 it and works fine.

And it seems the latest release (0.2.13) is not listed in the sidebar.

### Expected behavior

The page should work fine with no error 500.

### Platform and versions

```Shell
Google Chrome browser on a Windows 10. Although I'm pretty sure this issue happens to everyone.
```

### Additional context

I think the error is caused from https://github.com/spacedriveapp/spacedrive/blob/main/apps/landing/src/app/docs/changelog/%5Bcategory%5D/%5Btag%5D/page.tsx when fetching the releases/categories.

**Comment by utkubakir** [comment]
I believe it happens because the page is cached so we need to trigger a redeploy or cache invalidation after the release. Will fix the issue with a redeployment. Also created an issue for this so we can fix it permanently :)
