### ISSUE TITLE
Tags: no explicit way to update a tag color/name

### ISSUE THREAD

**Issue by zaaakher** [spacedriveapp/spacedrive#2418]
### Describe the bug

When I try to update the tag color/name there's no "save" button to save the changes I just made to the tag,

![spacedrive-save-tags-issue](https://github.com/spacedriveapp/spacedrive/assets/46135573/d8e53d74-de71-49b8-a051-76375f237339)

### Reproduction

1. Go to settings
2. Go to a library's tags
3. select an existing tag
4. change the color / name
5. try to save the changes you just made

### Expected behavior

There should be a button in `interface/app/$libraryId/settings/library/tags/EditForm.tsx` next to the delete button that executes the `updateTag.mutate()` when `onClick` is triggered in that button.

### Platform and versions

```Shell
Windows 10 Pro (19045.4291) - Spacedrive for Windows v0.2.13 93844bad
```

**Comment by zaaakher** [comment]
The only way I was able to update a tag name/color is by creating a new tag which I think triggers the `useDebouncFormWatch` hook

**Comment by utkubakir** [comment]
They are updated live (unless that's not working?), maybe we should show a toast to indicate that

**Comment by zaaakher** [comment]
Unfortunately they're not updated live.  If I change a color/name of a tag and then switch to another tag then the first tag I just updated doesn't retain the changes I made to it.

**Comment by utkubakir** [comment]
Can confirm. They are being updated in the background but sidebar is not getting updated...

**Comment by zaaakher** [comment]
Oh I didn't notice the sidebar part. I can confirm that the tag updates when I click on the tag in the sidebar. So in general it seems I have to do some action to trigger a UI update (like clicking on the tag from the sidebar or creating a new tag). 

It could be an opinionated suggestion but I think an explicit "Save" or "Update" button to save the changes made would actually feel more intuitive and might even be easier to implement. 

Nevertheless, here's a goofy little [video](https://youtu.be/torvqaPmELY) I just recorded to show the issue discussed in this issue.

**Comment by zaaakher** [comment]
I just tested it now and it seems to be working fine, the color changes when I select it and the text changes when I unfocus from the input element or click the enter key.

**Comment by utkubakir** [comment]
For future reference, this is probably related to million.js somehow, code looks fine.
