### ISSUE TITLE
"New Update Available" toast not disappearing after update

### ISSUE THREAD

**Issue by zaaakher** [spacedriveapp/spacedrive#2519]
### Describe the bug

I got a toast in the bottom right corner telling me there's a new update. After clicking on "update" and going to through the wizard and SpaceDrive opens up again the toast shows up again telling me to update again even though SpaceDrive is already the latest version.

I actually fell for it and updated SpaceDrive twice 😅

![image](https://github.com/spacedriveapp/spacedrive/assets/46135573/088e6655-efad-41b9-9314-872e8e1be17b)

### Reproduction

1. Make sure your SpaceDrive app is not up to date.
2. You'll see a "New Update Available" toast on the bottom right corner
3. Click on the "update" action button in that toast and go through the installation wizard
4. SpaceDrive will open up again after the update ( or you can open SpaceDrive manually)
5. You'll see the toast again even though your SpaceDrive is up to date.

### Expected behavior

The "New Update Available" toast should not appear again after updating SpaceDrive.

I think there should be a check to see if the SpaceDrive version the user has is up to date or not. If so, then don't show the toast, otherwise keep showing it every time they open the SpaceDrive app.

### Platform and versions

```Shell
Windows 10 Pro (Build 19045.4291)
pnpm: v9.1.3
cargo: n/a
rustc: n/a
```

**Comment by zaaakher** [comment]
I noticed the same thing with the "Install Update" button on the side menu. 👇 It seems to be that the function that detects if the app needs to be updated is not really detecting the current version of my app and matching it with the actual latest release of the SpaceDrive

![image](https://github.com/spacedriveapp/spacedrive/assets/46135573/e9808690-cf82-4bcf-970a-514c8689d6fc)

**Comment by zaaakher** [comment]
Tracing the issue back to where it could potentially be from:

Either from the desktop updater in [`desktop/src/updater.tsx`](https://github.com/spacedriveapp/spacedrive/blob/main/apps/desktop/src/updater.tsx)

Or from the tauri updater in [`desktop/src-tauri/src/updater.rs`](https://github.com/spacedriveapp/spacedrive/blob/4a62d268efea7dd6ff573531b1e2b2970c7ba562/apps/desktop/src-tauri/src/updater.rs#L46-L70)

**Comment by HeavenVolkoff** [comment]
I think this was solved by #2517, I am building a test release rn to make sure, will post the link here when it is available so any people experiencing this can test.

**Comment by zaaakher** [comment]
@HeavenVolkoff ok I downloaded the `Spacedrive-windows-x86_64.msi` file and installed it seems to be working fine with no toast or any msg telling me to update 👍 

Although on a side note that could be irrelevant:
During the installation of that test release I got this warning

![image](https://github.com/spacedriveapp/spacedrive/assets/46135573/8cc19abd-36ef-40fd-a65d-391f67e8e0c0)

**Comment by davidjaggi** [comment]
I experience the same issue. This was also an issue in an earlier release but the solved via an update.

**Comment by ketonik** [comment]
Nice work guys, resolved for me too
Spacedrive-windows-x86_64.msi
at
https://github.com/spacedriveapp/spacedrive/actions/runs/9292624870/artifacts/1550110422

Edition	Windows 11 Pro for Workstations
Version	23H2
Installed on	‎30/‎09/‎2023
OS build	22635.3646
Experience	Windows Feature Experience Pack 1000.22700.1013.0

**Comment by utkubakir** [comment]
Perfect, we will be pushing an update soon

**Comment by zaaakher** [comment]
Just tested it again with the official release v0.3.1 and this issue is resolved 👍 Thanks @HeavenVolkoff @utkubakir
