### ISSUE TITLE
Spacedrive suddenly crashes on Windows 11

### ISSUE THREAD

**Issue by surferjoeit** [spacedriveapp/spacedrive#2520]
### Describe the bug

I just installed latest release (alpha 0.3.0) and it always crashes after a few minutes every time i launch it

### Reproduction

Launch spacedrive and wait no more than 5 minutes.. it suddenly closes

### Platform and versions

```Shell
Microsoft Windows 11
```

**Comment by utkubakir** [comment]
Duplicate https://github.com/spacedriveapp/spacedrive/issues/2519

**Comment by surferjoeit** [comment]
I downloaded the test release but it still crashes. It just launches faster than the previous release. I made some additional tests and it crashes almost immediately when i open dropbox folder.  on other folders it takes  more time and on the "home" page it doesn't crash.
