### ISSUE TITLE
macOS version 0.3.0 downloads contain still version notation 0.2.13

### ISSUE THREAD

**Issue by suschizu** [spacedriveapp/spacedrive#2521]
### Describe the bug

the info.plist wasn't  updated to the correct version 

### Reproduction

download
https://github.com/spacedriveapp/spacedrive/releases/download/0.3.0/Spacedrive-darwin-x86_64.dmg
https://github.com/spacedriveapp/spacedrive/releases/download/0.3.0/Spacedrive-darwin-aarch64.dmg

### Expected behavior

<img width="462" alt="Screenshot 2024-05-30 at 00 31 15" src="https://github.com/spacedriveapp/spacedrive/assets/16004333/1e604b4c-3234-4726-8c06-5eede2bb1d12">

### Platform and versions

```Shell
macOS
```

**Comment by utkubakir** [comment]
Duplicate https://github.com/spacedriveapp/spacedrive/issues/2519
