### ISSUE TITLE
Tabs mask top most text in Settings

### ISSUE THREAD

**Issue by ketonik** [spacedriveapp/spacedrive#2529]
### Describe the bug

Little graphic oopsies:
In Settings, the Heading of each which in the case of Locations, also buttons are partially covered up by the Tabs.

![image](https://github.com/spacedriveapp/spacedrive/assets/49221849/d69f732e-7096-468a-b04c-eefa5f2164f2)
![image](https://github.com/spacedriveapp/spacedrive/assets/49221849/7c8abc22-e8aa-447a-abb0-dd00ec7ca8dd)

### Reproduction

Create some Tabs, Command+T
Go to settings,
Click Add Locations or any others, and you'll see as per screenshot above.

### Expected behavior

Maybe the page area of each setting needs to be pushed down the amount of pixels the tabs take up?

### Platform and versions

```Shell
SpaceDrive v0.3.0 4a62d26

Winblowz

Edition	Windows 11 Pro for Workstations
Version	23H2
Installed on	‎30/‎09/‎2023
OS build	22635.3646
Experience	Windows Feature Experience Pack 1000.22700.1013.0
```

**Comment by PineappleRind** [comment]
Can't reproduce on Spacedrive v0.4.1 (dbc7cd65), macOS 14.1; the tabs disappear when navigating to location settings

**Comment by ketonik** [comment]
> Can't reproduce on Spacedrive v0.4.1 ([dbc7cd6](https://github.com/spacedriveapp/spacedrive/commit/dbc7cd6547f3de5d9b7e7a407cc9216d1a4fadf0)), macOS 14.1; the tabs disappear when navigating to location settings

Must be just Windows version, happening in 0.4.1 here too, don't have amuch need to run spacedrive on my Mac, so haven't checked.
