### ISSUE TITLE
Desktop entry fails to get created on Arch AUR install

### ISSUE THREAD

**Issue by croots** [spacedriveapp/spacedrive#2534]
### Describe the bug

After stalling Spacedrive on AUR, no `spacedrive.desktop` file is created on the filesystem. `sudo find . -name spacedrive.desktop` from `/` fails to return anything. This prevents launchers from finding the program.

I may just be bad at using github's search functionality, but I can't find an example of the desktop file so I can't manually drop it in either.

I'm running Arch Linux and paru which would be the relevant software. I think the desktop file should be getting created regardless of my environment, but currently I'm on hyprland with no desktop environment as this is a recent distro hop.

Similar to #1475 except no file actually exists

### Reproduction

1. Install Spacedrive via `paru -S spacedrive`
2. Observe missing `spacedrive.desktop` file

### Expected behavior

`spacedrive.desktop` is created in `./usr/share/applications/firefox.desktop` during installation. An example file exists in the documentation for manual workarounds.

### Platform and versions

```Shell
9.1.4
cargo 1.78.0
rustc 1.78.0 (9b00956e5 2024-04-29) (Arch Linux rust 1:1.78.0-1)

Arch 255.7-1-arch
```

**Comment by HeavenVolkoff** [comment]
Hey @croots, the AUR release of spacedrive is made by a third party and not official. I ask that you report this issue to the maintainer of the package. Currently the only Debian-based Linux distros are officially supported. We are currently working on a flatpak release and a official release for Arch-linux based distros is planned, but not a priority.
