### ISSUE TITLE
Missing ddl in Installer

### ISSUE THREAD

**Issue by shyim** [spacedriveapp/spacedrive#254]
### Describe the bug

Hey,

the installer seems missing an avdevice-59.dll 
![image](https://user-images.githubusercontent.com/6224096/174433593-2338ff11-149a-43ea-829c-e43a1546a2d6.png)

### Reproduction

- Install the CI Artifact in Windows 11

### Platform and versions

```Shell
Windows 11 Build 22000.739
```

**Comment by waydealphax** [comment]
on windows, ffmpeg needs additional setup as (in my testing), the pre-compiled versions of ffmpeg for windows dont actually include everything needed as their own bins. you'll have to self compile and update your path (atleast thats what I did)

**Comment by oscartbeaumont** [comment]
We are going to need to look into this then because a user definitely can't be expected to install Ffmpeg alongside the app. Currently, the team is focusing on building out the app but when I can find some time probably closer to use launching the MVP, I will give this a look and come up with a solution.

**Comment by waydealphax** [comment]
Yeah totally, and it doesn't help that FFMPEG is packaged differently for windows as well, if you want some windows battle testing closer to the time I've got no issues with that.

**Comment by voletro** [comment]
PR #321 should fix this, as the setup script will copy the required .dll files from the downloaded ffmpeg build to the target\debug folder. That folder is where the .dll files are needed for ffmpeg-rust to build successfully.

Building will be another issue, but I assume we will tackle that once building an MVP is needed.

**Comment by waydealphax** [comment]
Yeah totally, and it doesn't help that FFMPEG is packaged differently for
windows as well, if you want some windows battle testing closer to the time
I've got no issues with that.

**Comment by niuggg** [comment]
good  thankyou
