### ISSUE TITLE
Segfault on Nvidia with X11

### ISSUE THREAD

**Issue by username227** [spacedriveapp/spacedrive#2541]
### Describe the bug

Program segfaults when opening with x11. Issue is related to this rust problem: https://internals.rust-lang.org/t/global-symbols-from-statically-linked-system-libraries/19954
Problem is present when running on nvidia card, and is not an issue with your program per se (see easy proposed fix  below).

### Reproduction

Start program with nvidia graphics on x11

### Expected behavior

program should open normally.

### Platform and versions

```Shell
Arch / Cinnamon / Nvidia.
```

### Stack trace

```Shell
backtrace:
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffda8006c0 (LWP 110506)]
[New Thread 0x7fffda4006c0 (LWP 110507)]
[New Thread 0x7fffda0006c0 (LWP 110508)]
[New Thread 0x7fffd9c006c0 (LWP 110509)]
[New Thread 0x7fffd98006c0 (LWP 110510)]
[New Thread 0x7fffd94006c0 (LWP 110511)]
[New Thread 0x7fffd90006c0 (LWP 110512)]
[New Thread 0x7fffd8c006c0 (LWP 110513)]
[New Thread 0x7fffd88006c0 (LWP 110514)]
[New Thread 0x7fffd84006c0 (LWP 110515)]
[New Thread 0x7fffd3e006c0 (LWP 110516)]
[New Thread 0x7fffd3a006c0 (LWP 110517)]
[New Thread 0x7fffd36006c0 (LWP 110518)]
[New Thread 0x7fffd2c006c0 (LWP 110519)]
[New Thread 0x7fffd22006c0 (LWP 110520)]
[New Thread 0x7fffd14006c0 (LWP 110521)]
[New Thread 0x7fffd10006c0 (LWP 110522)]
[New Thread 0x7fffc5e006c0 (LWP 110523)]
[New Thread 0x7fffc54006c0 (LWP 110524)]
[Detaching after vfork from child process 110525]

Thread 1 "spacedrive" received signal SIGSEGV, Segmentation fault.
0x00007fffedc71434 in pthread_mutex_lock () from /usr/lib/libc.so.6
```

### Additional context

The program will start normally with the following environment variable: WEBKIT_DISABLE_DMABUF_RENDERER=1
I have fixed the spacedrive-bin package on the AUR. You should consider adding this to the desktop file Exec to avoid issues until rust fixes the problem.

**Comment by HeavenVolkoff** [comment]
Hey, thanks for reporting this issue. Can you try building this PR: #2542 and running without explicitly setting `WEBKIT_DISABLE_DMABUF_RENDERER` to see if it works

**Comment by username227** [comment]
hmmm....it's possible I did something wrong during compiling, but this version doesn't seem to work at all, both with and without the variable I get a segfault...

**Comment by username227** [comment]
this branch DOES still work on Wayland. on x11 gives segfault (similar backtrace) now both with and without the environment variable.

**Comment by username227** [comment]
I can also confirm that the executable from this branch also DOES work if the nvidia card is not used - on integrated AMD GPU with X11. So whatever's going on is still definitely related to this issue.

**Comment by HeavenVolkoff** [comment]
Updated the PR, @username227 can you try again?

**Comment by username227** [comment]
Appears to start properly now. Great work.

**Comment by HeavenVolkoff** [comment]
@username227 I updated the PR again. I think that now that we are not statically compiling dbus into the app, it should run fine on Nvidia, even without the `WEBKIT_DISABLE_DMABUF_RENDERER` env var being set internally, as I was previously doing. Could you try it again to make sure it continues to work properly?

**Comment by username227** [comment]
OK; with the environment variable, it works normally.
without the environment variable, it no longer segfaults, but graphics do not come up properly either. I get the following error:

AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer

which seems to  repeat until I close the window.

**Comment by HeavenVolkoff** [comment]
> AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer

Hun, seems like this is a known issue:
https://github.com/tauri-apps/tauri/issues/9304

Most likely, something is broken in webkit2gtk. I will put back the code to inject `WEBKIT_DISABLE_DMABUF_RENDERER` when running under Nvidia on Linux, as that seems to be the best alternative for now.

@username227 thanks for the help with the tests.

**Comment by username227** [comment]
makes sense. I'm not convinced that it's really the fault of webkit2gtk. I think it's a combination of the interaction of rust, tauri, and webkit2gtk. good thing they have the workaround is all I can say.

**Comment by HeavenVolkoff** [comment]
Hey, @username227 I updated the logic for detecting nvidia cards (replaced gl/glfw with wgpu), could you give it a test to check if it is still working properly...

**Comment by username227** [comment]
@HeavenVolkoff Yes, still works.
