### ISSUE TITLE
Quick preview audio player does not reappear after switching to non-audio file and back.

### ISSUE THREAD

**Issue by gibsh** [spacedriveapp/spacedrive#2543]
### Describe the bug

When switching away to a non-audio file in the quick view, the audio player does not reappear if you move back to an audio file.

![image](https://github.com/spacedriveapp/spacedrive/assets/72422556/7131595e-9a44-4e37-8eab-a2b75b8f7850)

### Platform and versions

```Shell
Windows 10 (22H2 19045) & Spacedrive v0.3.1
```

**Comment by iLynxcat** [comment]
Reproduced, though it didn't happen when switching from audio to photo to audio — it did happen switching from audio to zip to audio

**Comment by MadisonKonig** [comment]
Pulled and synced before working on it some more...I think this might have been fixed with someone else's commits/pushes? Anyone else mind confirming?

**Comment by HeavenVolkoff** [comment]
> Pulled and synced before working on it some more...I think this might have been fixed with someone else's commits/pushes? Anyone else mind confirming?

Yes, I fixed this on #2758, thanks for the ping. Completely forgot to link the PR to this issue, will close it now.
