### ISSUE TITLE
Discord invite on app first launch expired 

### ISSUE THREAD

**Issue by jasonbrown1965** [spacedriveapp/spacedrive#2545]
### Describe the bug

Just installed Spacedrive. 
Clicked Discord button.*
Got "Invite Invalid" error. 

![image](https://github.com/spacedriveapp/spacedrive/assets/11400799/baa26282-d45d-48f9-b8b9-374848b10aa1)

* https://discord.com/invite/ukRnWSnAbG

### Reproduction

Fresh install app
Click discord link on install launch page, as above

### Expected behavior

Launch Discord page or desktop app from SpaceDrive desktop app. 

### Platform and versions

```Shell
Window 10 19045 fully updated.
```

### Additional context

No biggie!

**Comment by utkubakir** [comment]
fixed on #2550
