### ISSUE TITLE
Trash isn't opening on Linux

### ISSUE THREAD

**Issue by gedeondoescode** [spacedriveapp/spacedrive#2546]
### Describe the bug

Trash directory doesn't open

### Reproduction

1. Open Spacedrive
2. Click Trash
3. Nothing appears

### Expected behavior

Trash folder should open in the default xdg application

### Platform and versions

```Shell
pnpm 9.2.0
cargo 1.78.0 (54d8815d0 2024-03-26)
rustc 1.78.0 (9b00956e5 2024-04-29)
```

**Comment by kk-rishang** [comment]
+1
