### ISSUE TITLE
The "Recents" tab is not functioning properly.

### ISSUE THREAD

**Issue by samurai00** [spacedriveapp/spacedrive#2571]
### Describe the bug

The "Recents" tab only displays files upon the initial launch of app. Once I switch to another tab, such as Overview or Favorites, and then switch back to Recents, it shows a blank page with no files listed. In this scenario, when switching away from the Recents tab, there is a brief moment where the files appear before the content of the other tab is shown.

### Reproduction

1. Open Spacedrive.app
2. Click "Recents"
3. Click "Overview"
4. Click "Recents"
<img width="1084" alt="截屏2024-06-19 20 37 26" src="https://github.com/spacedriveapp/spacedrive/assets/685874/0ed5892c-1e87-4bc0-9d10-323d958cf046">
<img width="1084" alt="截屏2024-06-19 20 37 29" src="https://github.com/spacedriveapp/spacedrive/assets/685874/7a324801-96e5-4111-ba70-d198a04b64a2">

<img width="1084" alt="截屏2024-06-19 20 37 34" src="https://github.com/spacedriveapp/spacedrive/assets/685874/0571a263-30e5-4849-acad-e23a080a08b0">
<img width="1084" alt="截屏2024-06-19 20 37 36" src="https://github.com/spacedriveapp/spacedrive/assets/685874/a9cab6ac-3442-44b4-84e6-f3862b067a26">

### Platform and versions

```Shell
macOS Sonoma 14.5 arm64
Apple Silicon M1 Pro

Spacedrive: Version 0.3.1 (20240531.213255)

❯ pnpm --version && cargo --version && rustc --version
9.1.1
cargo 1.78.0 (54d8815d0 2024-03-26)
rustc 1.78.0 (9b00956e5 2024-04-29)
```

**Comment by ameer2468** [comment]
Thank you for the report - will be fixed asap!
