### ISSUE TITLE
unable to resize the window on windows

### ISSUE THREAD

**Issue by HeavySnowJakarta** [spacedriveapp/spacedrive#2587]
### Describe the bug

when the program launches the size of the window is too huge for me (high ppi screen) and on v3.0.1 it's not able to resize.

what's more, during the launch it's better to restore the window size of when it's closed.

### Platform and versions

```Shell
Alpha 0.3.1

windows-x86_64
```

**Comment by iLynxcat** [comment]
is this still happening in v0.4.0? if so we will look into it.

**Comment by HeavySnowJakarta** [comment]
> is this still happening in v0.4.0? if so we will look into it.

I can confirm this issue still exists on my computer

**Comment by iLynxcat** [comment]
gotcha. I'm gonna have someone on our team who has a Windows install try to repro this and will report back shortly

**Comment by ketonik** [comment]
In the meantime ALT+Drag lets you drag any window from any space in the window.
https://stefansundin.github.io/altdrag/

**Comment by ameer2468** [comment]
This has improved a lot recently on 0.4.2 - can you please confirm?

I was able to reproduce this issue, but now it no longer exists :)

**Comment by ketonik** [comment]
> This has improved a lot recently on 0.4.2 - can you please confirm?
> 
> I was able to reproduce this issue, but now it no longer exists :)

Confirmed here, resizing window on Windoze now functioning thx
