### ISSUE TITLE
ToggleSidebar and NavigateBack keybind conflict in windows

### ISSUE THREAD

**Issue by blanit** [spacedriveapp/spacedrive#2605]
### Describe the bug

Toggle Sidebar with default keybind "[", and Navigate Back with default keybind "ctrl + ["
both have [ and cause the conflict, which Toggle Sidebar when use Navigate Back

### Platform and versions

```Shell
windows app v0.3.1
```

**Comment by iLynxcat** [comment]
Thanks for the report, we're looking into it!

**Comment by ameer2468** [comment]
Fixed here: https://github.com/spacedriveapp/spacedrive/pull/2625

Thank you for the report.
