### ISSUE TITLE
Windows Defender Reports 0.4.0 Package As Virus

### ISSUE THREAD

**Issue by pldmgg** [spacedriveapp/spacedrive#2620]
### Describe the bug

Downloading 0.4.0 Spacedrive-windows-x86_64.msi on Windows 11 causes Windows Defender to immediately delete the package claiming it is a virus. Also, uploading Spacedrive-windows-x86_64.msi to https://www.hybrid-analysis.com/ reports it as malicious as well.

### Platform and versions

```Shell
Windows 11 23H2
```

**Comment by iLynxcat** [comment]
thanks for the report. based on Hybrid Analysis's report it looks like it's just one of 24 (Cylance) that's reporting it malicious. the CrowdStrike Falcon (lol) sandbox shows nothing. it doesn't look like we ever got code signing set up properly on Windows, though it's in the works and we plan to have Windows signing set up by release 1.0, we've seen it as less important during alpha.
