### ISSUE TITLE
Add keybind to duplicate current tab

### ISSUE THREAD

**Issue by iLynxcat** [spacedriveapp/spacedrive#2621]
### Discussed in https://github.com/spacedriveapp/spacedrive/discussions/2614

<div type='discussions-op-text'>

<sup>Originally posted by **ShrineFox** July 18, 2024</sup>
It would be cool if there was an option (maybe a separate keybind like CTRL+SHIFT+T) to instantaneously make a duplicate of the current tab.</div>

**Comment by deysandip301** [comment]
Hey @iLynxcat I am new to contributing and I would like to work on this issue 
can you please assign this issue to me ?

**Comment by iLynxcat** [comment]
Hey @deysandip301, welcome to the Spacedrive community and thanks for contributing 👋

I'll go ahead and assign this issue to you so nobody works on a duplicate PR, and we look forward to seeing and giving feedback on your PR soon :)

<sub>Please make sure to read our [Contributing Guide](https://github.com/spacedriveapp/spacedrive/blob/3abd1d72e81a03f8576ecc5823d6e60f141cee95/CONTRIBUTING.md) and [Code of Conduct](https://github.com/spacedriveapp/spacedrive/blob/3abd1d72e81a03f8576ecc5823d6e60f141cee95/CODE_OF_CONDUCT.md) before contributing.</sub>

**Comment by iLynxcat** [comment]
Hi @deysandip301, are you still planning to contribute this feature? There's no pressure to do so if you are not feeling like it anymore — just figuring out whether I should reopen this to others!

**Comment by yaodada123** [comment]
Hi， @iLynxcat I think I can also complete this task, of course if I am allowed to do it

**Comment by iLynxcat** [comment]
Hi @yaodada123 — of course, contributions are always welcome! I've taken @deysandip301 off of the issue, and if you would like to work on this issue you are welcome to open a pull request. Thank you for your interest in contributing!

**Comment by MadisonKonig** [comment]
Hi @iLynxcat, for this, when duplicating the tab, are you wanting the original tab's history to copy over as well, or is a fresh start fine?

**Comment by iLynxcat** [comment]
I don't believe copying history is important. If once the feature is implemented we get feedback from users stating otherwise we can always go back and implement it

**Comment by MadisonKonig** [comment]
the original shortcut was suggested to be CTRL SHIFT T, but that seems to be in use for opening up the settings menu.  Would Ctrl Shift N work instead?
![image](https://github.com/user-attachments/assets/b091b10d-f150-4dd7-9920-316f7a3f295f)

**Comment by iLynxcat** [comment]
Unless the convention is different on Linux (any insight @matheus-consoli?) I think the expectation on all platforms is that settings is opened via <kbd>Cmd/Ctrl</kbd>+<kbd>,</kbd>. Though I think <kbd>Cmd/Ctrl</kbd>+<kbd>Opt/Alt</kbd>+<kbd>T</kbd> makes more sense for this shortcut, we should look into why we decided on cmd+shift+t for that shortcut

**Comment by iLynxcat** [comment]
Silly me, that's used for tag assign mode. I think for now cmd+shift+n is fine like you suggested and we can discuss internally what we actually want before we merge the PR.
