### ISSUE TITLE
Landing (TeamPage) Social Links different height

### ISSUE THREAD

**Issue by CreatingBytes** [spacedriveapp/spacedrive#264]
### Describe the bug

On the Team page the Social Links have a different height. Jamie's social links are lower from the height than the others.

![Screenshot_5](https://user-images.githubusercontent.com/34302688/174662245-57e524c0-7481-4d71-8873-addb226ebb5f.png)

### Expected behavior

They should be all on the same height

![Screenshot_6](https://user-images.githubusercontent.com/34302688/174662850-2914cb9d-708a-4e32-a294-69c4a79a7180.png)

### Platform and versions

```Shell
pnpm 7.3.0
cargo 1.61.0 (a028ae42f 2022-04-29)
rustc 1.61.0 (fe5b13d68 2022-05-18)

Windows 10 Version 21H2
```

**Comment by oscartbeaumont** [comment]
Fixed in #265.
