### ISSUE TITLE
Debian package references incorrect executable name

### ISSUE THREAD

**Issue by stephanschindel** [spacedriveapp/spacedrive#2647]
### Check for other issues

- [X] I've checked for other issues, and none exist.

### Issue description

When I install Spacedrive 0.4.1 on Debian Bookworm, there is no desktop icon for Spacedrive (e.g. GNOME -> Applications).

I guess reason for that is that the spacedrive.desktop is referring to sd-desktop:

Exec=sd-desktop

But only /usr/bin/spacedrive is available, /usr/bin/sd-desktop not.

Naming issue?

### Steps to reproduce

Install debian package for spacedrive 0.4.1.

Look in the default applications menu and search for spacedrive.

### Platform and versions

- OS: Debian 12
- Spacedrive: 0.4.1

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by iLynxcat** [comment]
interesting, will look into this asap! I know on Windows our executable is named sd-desktop.exe and I believe the executable is sd-desktop on macOS too, so I'd expect it to build the same way. we'll get looking into this shortly!

**Comment by HeavenVolkoff** [comment]
Confirmed, this bug is present in both 0.4.0 and 0.4.1, just pushed a PR with a fix, will replace the 0.4.1 deb with a fixed one as soon as CI builds a new release

**Comment by HeavenVolkoff** [comment]
@stephanschindel thanks for the report. The `.deb` file for the [0.4.1 release](https://github.com/spacedriveapp/spacedrive/releases/tag/0.4.1) was replaced with one containing a fix for this issue.
