### ISSUE TITLE
Tag assign mode not working as expected

### ISSUE THREAD

**Issue by marsjane** [spacedriveapp/spacedrive#2658]
### Check for other issues

- [X] I've checked for other issues, and none exist.

### Issue description

When I click the tog assign mode button, it shows message like `select files and press number to assign tag`, but there is no number for these tags, so don't know how to use the tag mode, you can see the screenshot
![Shot 2024-08-13 at 09 33 31@2x](https://github.com/user-attachments/assets/f53eaa21-31d2-41d8-a948-35b0ec435076)

### Steps to reproduce

just click the tag assign mode button

### Platform and versions

- OS: MacOS 14.6.1
- Spacedrive: Version 0.4.1 （20240726.220037）

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by valeriewong052** [comment]
Hi - You just have to select the tag button itself first and assign a number, before the number then can be used to tag files! 

I agree that it's a little confusing since the tags don't currently have numbers by default. We'll look at improving the UI/description of this!
