### ISSUE TITLE
Unknown job type - Clean install and scan desktop crashes spacedrive

### ISSUE THREAD

**Issue by TwanLuttik** [spacedriveapp/spacedrive#2686]
### Check for other issues

- [X] I've checked for other issues, and none exist.

### Issue description

In the log file i assume this is the line that causes my spacedrive to crash while its scanning my desktop which has quite some files on it.

`2024-08-20T20:18:49.699357Z ERROR load{library_id=42ca9d90-5a56-4944-a6aa-706cb0a51d5f db_path=/Users/twanluttik/Library/Application Support/spacedrive/libraries/42ca9d90-5a56-4944-a6aa-706cb0a51d5f.db config_path=/Users/twanluttik/Library/Application Support/spacedrive/libraries/42ca9d90-5a56-4944-a6aa-706cb0a51d5f.sdlibrary should_seed=true}: sd_core::old_job::manager: core/src/old_job/manager.rs:400: Unknown job type; job_report.name=media_processor job_report.id=0683dc13-ae71-4c9a-b84d-07568c71d94b`

[sd.log.2024-08-20.txt](https://github.com/user-attachments/files/16681396/sd.log.2024-08-20.txt)

### Platform and versions

- OS: 14.6.1
- Spacedrive: 0.4.2

<details><summary> Development tool versions (optional) </summary><pre>

</pre></details>

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by TwanLuttik** [comment]
And when i open the location in spacedrive, it cause the same crash and error.

**Comment by TwanLuttik** [comment]
I think Haden is on this as well but we found out which specific file it causes to crash spacedrive.

https://github.com/user-attachments/assets/e01a7ddc-8760-4896-8716-7e46f009ff7e

**Comment by HeavenVolkoff** [comment]
Is your Mac a M1 Mac? If so, I think this is probably the same crash that a user was experiencing on discord on M1 with HEVC files (considering the file you uploaded is a HEVC). This was fixed in https://github.com/spacedriveapp/native-deps/releases/tag/v0.23. However, the fix is not present in a stable release yet. Can you try compiling main to see if the crash stops?
