### ISSUE TITLE
The button of closing the window may disappear due to the size

### ISSUE THREAD

**Issue by HeavySnowJakarta** [spacedriveapp/spacedrive#2689]
### Check for other issues

- [X] I've checked for other issues, and none exist.

### Issue description

#2587 solved but...

![图片](https://github.com/user-attachments/assets/2d4d73b4-dd04-43d4-b4a4-165808cf4621)

Not reopening the issue above cuz it's actually another problem

### Steps to reproduce

* Open a new window
* Then drag it to a smaller size

### Platform and versions

- OS: Windows 11 23H2
- Spacedrive: 3.4.2 via `winget`

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by ameer2468** [comment]
Thank you for the report - will fix this.
