### ISSUE TITLE
Beta 0.5 ???

### ISSUE THREAD

**Issue by pnoelfr** [spacedriveapp/spacedrive#2698]
### Check for other issues

- [X] I've checked for other issues, and none exist.

### Issue description

hi
Somes News about the 0.5 Beta ???

### Platform and versions

- OS:
- Spacedrive:

<details><summary> Development tool versions (optional) </summary><pre>

</pre></details>

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by ameer2468** [comment]
Hello,

The features of Cloud & Sync + the Mobile app are WIP. Once they are ready we will be releasing 0.5.

You can check for related PRs here: https://github.com/spacedriveapp/spacedrive/pulls

Thanks you!
