### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by abhnva** [spacedriveapp/spacedrive#27]
Can I install this now?

**Comment by Pierstoval** [comment]
@oscartbeaumont I have a suggestion, even though the ticket is closed:

Can the green builds be published as artifacts in the CI? This would help using sort of "latest builds" as installable binaries. I saw that the .msi files can be properly built and used, so why not? 😉 (can contribute this if you like)

**Comment by oscartbeaumont** [comment]
@Brendonovich is already on that. He is having some CI issues with Rust related to caching so we haven't got that CI working on the main repo yet.

Although even if you could get CI artifacts the app isn't ready for general use.
