### ISSUE TITLE
Handle leak in Windows

### ISSUE THREAD

**Issue by tedd** [spacedriveapp/spacedrive#2725]
### Check for other issues

- [X] I've checked for other issues, and none exist.

### Issue description

When Spacedrive index new locations, its handle count increases and does not decrease again. This causes Windows to slow down.

### Steps to reproduce

1. Open Task Manager, choose to show Handles column, observe sd-desktop.exe
2. Click on Add Location, select location with lots of files
3. Observe Handles count increase

### Platform and versions

- OS: Windows 11
- Spacedrive: v0.4.2 - 0af8dbf

<details><summary> Development tool versions (optional) </summary><pre>

</pre></details>

### Additional context

High handle count in Windows will make the OS slow. It does not show up on any CPU time measurement, but the whole machine feels sluggish. When I noticed it was slow, I found Spacedrive having nearly 500.00 handles open. Killing the process fixed the issue (after a minute or so).

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by tedd** [comment]
![image](https://github.com/user-attachments/assets/dac7f3bb-a6c9-40b7-8440-8ae4382eb89e)
Handle count is higher than number of files. Even higher considering .git and .gitignore in folders.

**Comment by iLynxcat** [comment]
we've pinpointed the cause of this and have a PR up for a fix! props to @matheus.consoli7 and @ericson.ds999 for taking care of this so quickly 🔥
