### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by paulyhedral** [spacedriveapp/spacedrive#2763]
### Check for other issues

- [X] I've checked for other issues, and none exist.

### Issue description

Login redirects to https://api.spacedrive.com/login/device?userCode=REDACTED&device=desktop, which results in "This site can't be reached" (`DNS_PROBE_FINISHED_NXDOMAIN`).

### Steps to reproduce

1. Click "Feedback"
2. Click "Login"
3. Browser window opens, but site is not found

### Platform and versions

- OS: macOS Sequoia 15.0.1
- Spacedrive: 0.4.2 (20240817.232038)

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by HeavenVolkoff** [comment]
Hi @paulyhedral, The Spacedrive account implemented in the latest released version didn't provide any extra feature, and it was removed. We are currently working in a complete rewrite for the account system that will implement cloud sync and remote access to your libraries between multiple desktop and mobile Spacedrive clients: https://github.com/spacedriveapp/spacedrive/pull/2633. This is still being developed and will come out in v0.5.0.
