### ISSUE TITLE
Scrollbar not reachable (Windows 10, DPI scaling 200%)

### ISSUE THREAD

**Issue by teadrinker** [spacedriveapp/spacedrive#2785]
### Check for other issues

- [X] I've checked for other issues, and none exist.

### Issue description

Scrollbar is not reachable (Windows 10, DPI scaling 200%)
![scroll](https://github.com/user-attachments/assets/3f4b6ce3-7a90-4852-b11d-6e684448c283)

### Steps to reproduce

Try to use scrollbar.
I can use mousewheel to scroll, but that workflow is not feasible for large folders.

### Platform and versions

- OS: Windows 10
- Spacedrive: v0.4.2

<details><summary> Development tool versions (optional) </summary><pre>

</pre></details>

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by iLynxcat** [comment]
This was fixed in development by @ameer2468, and will be included in the next release!
