### ISSUE TITLE
[ENG-210] Sidebar is transparent with no blur on Linux

### ISSUE THREAD

**Issue by mmattbtw** [spacedriveapp/spacedrive#341]
### Describe the bug

The sidebar for Spacedrive is transparent and not blurred like it's supposed to be (specifically on macOS).

### Reproduction

1. `git pull && pnpm i && pnpm prep && pnpm desktop dev`
2. Observe sidebar

### Expected behavior

I'd assume that the sidebar background would just be a solid color because I don't think blur can be native on Linux (or Windows).

### Platform and versions

```Shell
➜  spacedrive git:(main) pnpm --version && cargo --version && rustc --version
7.5.2
cargo 1.61.0 (a028ae4 2022-04-29)
rustc 1.61.0 (fe5b13d68 2022-05-18)
```

```
➜  spacedrive git:(main) neofetch
             /////////////                matt@pop-os 
         /////////////////////            ----------- 
      ///////*767////////////////            MS-7B98 1.0 
    //////7676767676*//////////////          Pop!_OS 22.04 LTS 
   /////76767//7676767//////////////         6 hours, 34 mins 
  /////767676///*76767///////////////        kitty 
 ///////767676///76767.///7676*///////       Catppuccin-Macchiato-Dark-BL 
/////////767676//76767///767676////////      12.32GiB / 31.29GiB (39%) 
//////////76767676767////76767/////////      Lil B - The Frozen Tape - Patrick Star 
///////////76767676//////7676//////////
////////////,7676,///////767///////////                           
/////////////*7676///////76////////////                           
///////////////7676////////////////////
 ///////////////7676///767////////////
  //////////////////////'////////////
   //////.7676767676767676767,//////
    /////767676767676767676767/////
      ///////////////////////////
         /////////////////////
             /////////////

```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by voletro** [comment]
This also happened to me on Windows. 
I fixed it by changing the default value of this useState from 'macOS' to 'windows' [here](https://github.com/spacedriveapp/spacedrive/blob/cc3c63b996651b518027e2e1bb1babcca52f64ee/apps/desktop/src/index.tsx#L48).

I think this variable isn't being set properly [here](https://github.com/spacedriveapp/spacedrive/blob/cc3c63b996651b518027e2e1bb1babcca52f64ee/apps/desktop/src/index.tsx#L51-L54).

**Comment by oscartbeaumont** [comment]
A while back I redid the variable that controls this behavior so potentially that or any other change could have fixed it which might explain if you can't reproduce it.

Is anyone still having this?

**Comment by brxken128** [comment]
iirc the very first library creation page was transparent, but the sidebar is fully opaque (on fedora 37, gnome 43)

![image](https://user-images.githubusercontent.com/77554505/195064238-d5d4cb51-2cab-487e-8d48-e1feff133181.png)

**Comment by oscartbeaumont** [comment]
Although that screenshot @brxken128 shared has way too much padding above the library switcher which is a bug.

**Comment by maxichrome** [comment]
awesome, will make the library switcher padding a separate thing
