### ISSUE TITLE
[BUG] Highlighted icons share their color globally

### ISSUE THREAD

**Issue by KodingDev** [spacedriveapp/spacedrive#38]
**Describe the bug**
When selecting a file in the file browser, all icons change color instead of respecting their color per-file.

**To Reproduce**
1. Import a library
2. Select a file with a custom icon & color in a folder where multiple of these exist

**Expected behavior**
The color is unique per icon and doesn't change across clicks.

**Screenshots**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/23714764/165659619-c37d960c-28d7-4288-9902-0631a562075f.png">
<img width="396" alt="image" src="https://user-images.githubusercontent.com/23714764/165659652-0e1b7819-d473-41a1-815b-bf4ed4f80ab3.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.2.1 (21D62)
 - Device: MacBook Air (M1, 2020)

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by jamiepine** [comment]
Thanks for documenting this one, it's been driving me mad for a while. The SVG loader seems to be buggy.
