### ISSUE TITLE
[BUG] Build failed: thread 'main' panicked at 'Unable to find libclang

### ISSUE THREAD

**Issue by luigibarbato** [spacedriveapp/spacedrive#44]
**Describe the bug**
Panic occured during cargo build.

**To Reproduce**

1. $ cd spacedrive
2. $ pnpm i
3. $ pnpm prep

**Expected behavior**
Success Cargo Build

**Screenshots**
![image](https://user-images.githubusercontent.com/50343470/165735059-4e6481ea-6f04-41d7-a374-cf1c00e696a6.png)

**Desktop (please complete the following information):**
 - OS: EndeavourOS Linux x86_64
 - Toolchain: rustc 1.61.0-nightly (76d770ac2 2022-04-02)

**Comment by oscartbeaumont** [comment]
Do you have `clang` installed? I don't know much about EndeavourOS but try installing [this](https://archlinux.org/packages/?name=clang).

**Comment by luigibarbato** [comment]
> Do you have `clang` installed? I don't know much about EndeavourOS but try installing [this](https://archlinux.org/packages/?name=clang).

Yep! It was the problem! It should be a requirement to add in README?

**Comment by oscartbeaumont** [comment]
@luigibarbato how did you install the `ffmpeg` deps? I am building a script to help people set up the Spacedrive dev environment.

**Comment by luigibarbato** [comment]
> @luigibarbato how did you install the `ffmpeg` deps? I am building a script to help people set up the Spacedrive dev environment.

I install the deps with the default system package manager (pacman). But for the purpose, I suggest to use [asdf](https://github.com/asdf-vm/asdf) so everyone will have the same dev environment

**Comment by oscartbeaumont** [comment]
I have made a [CONTRIBUTING.md](https://github.com/spacedriveapp/spacedrive/blob/contrib-guide/CONTRIBUTING.md#make-changes-locally) and [setup-system.sh](https://github.com/spacedriveapp/spacedrive/blob/contrib-guide/.github/scripts/setup-system.sh).

The script uses `pacman` for simplicity as that's what the Tauri docs use. It would be great if I could get your pacman install command so I can add it to that script.
