### ISSUE TITLE
Running `pnpm prep` results in no such command: `prisma`

### ISSUE THREAD

**Issue by pauliesnug** [spacedriveapp/spacedrive#488]
### Describe the bug

After running the install script and installing the latest version of rust with rustup, when running `pnpm prep` it results in gen:prisma failing with no such command: `prisma`. I'm on an M1 mac but even when using `rustup run stable-x86_64-apple-darwin cargo generate prisma` the command still throws an error.

### Platform and versions

```Shell
7.18.2
cargo 1.66.0 (d65d197ad 2022-11-15)
rustc 1.66.0 (69f9c33d7 2022-12-12)
OSX 13.0.1, M1 MacBook
```

### Stack trace

```Shell
> @sd/root@0.0.0 prep /Users/paulie/Personal/spacedrive
> pnpm gen:prisma && cargo test -p sd-core api::tests::test_and_export_rspc_bindings -- --exact

> @sd/root@0.0.0 gen:prisma /Users/paulie/Personal/spacedrive
> cd core && cargo prisma generate

error: no such command: `prisma`

	View all installed commands with `cargo --list`
 ELIFECYCLE  Command failed with exit code 101.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by brxken128** [comment]
Have you ran `pnpm i` prior to this?

**Comment by pauliesnug** [comment]
Yeah, here's the output
```
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 1.5s
```

**Comment by brxken128** [comment]
Thank you. Have you ran the setup script? If so, please could you run `rm -rf node_modules && cargo clean && pnpm i && pnpm prep && pnpm desktop dev` from the project root and see what the output is?

If needs be, a repo re-clone may solve it - it's fixed quite a few oddities such as this in the past for me.

**Comment by pauliesnug** [comment]
@brxken128 A repo re-clone solved it - where is the `prisma` command added to cargo, maybe that could be the issue since I modified some files beforehand?

**Comment by brxken128** [comment]
> @brxken128 A repo re-clone solved it - where is the `prisma` command added to cargo, maybe that could be the issue since I modified some files beforehand?

I think the binary itself ends up in `target` as `target/debug/prisma-cli`, and `cargo` recognizes it through an alias set in `.cargo/config.toml`. This kind of issue does happen every so often for seemingly no reason sadly.

**Comment by pauliesnug** [comment]
Thank you so much!
