### ISSUE TITLE
[BUG] Linux install fails with incorrect Node version

### ISSUE THREAD

**Issue by nlopez99** [spacedriveapp/spacedrive#49]
Building from source using Node 17.9.0 yields:
```bash
Your Node version is incompatible with "/amqplib/0.5.2".

Expected version: >=0.8 <=9
Got: v17.9.0

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
```

**To Reproduce**
1. Clone the repo
2. Run `pnpm i`
3. See error

**Expected behavior**
The install to succeed.

**Screenshots**
![image](https://user-images.githubusercontent.com/30613665/165812261-6bd4e900-44d1-459f-8b9b-e15add161cb9.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux 5.17

**Comment by abhnva** [comment]
Maybe try updating node?

**Comment by abhnva** [comment]
How did you install nodejs btw?

**Comment by abhnva** [comment]
https://github.com/nodejs/help/wiki/Installation

**Comment by abhnva** [comment]
https://nodejs.org/en/download/current/

**Comment by he1d1** [comment]
This seems odd, I don't think its a Node error.
The same Node version works for me so I'm gonna guess that your pnpm version is old, try running:

```bash
$ pnpm update --global pnpm
```
