### ISSUE TITLE
[FEATURE] NextCloud integration

### ISSUE THREAD

**Issue by zbraniecki** [spacedriveapp/spacedrive#51]
Do you anticipate to incorporate NextCloud integration?

**Comment by oscartbeaumont** [comment]
It could possibly be added as a cloud storage service in the future. We are currently not at that stage yet but we will look into it when we get to that stage.

**Comment by compgeniuses** [comment]
this will be fantastic, and it will be true one solution to view all files everywhere.

**Comment by oscartbeaumont** [comment]
I am closing this in favour of #95
