### ISSUE TITLE
[BUG] - local installation failed

### ISSUE THREAD

**Issue by Tchoupinax** [spacedriveapp/spacedrive#58]
Hello,

I want to start the project in local to take a look but I met this issue. Do not really know what is the issue.

**Describe the bug**
```
あ→ pnpm prep

> spacedrive@0.0.0 prep /tmp/spacedrive
> pnpm db:gen && pnpm core codegen


> spacedrive@0.0.0 db:gen /tmp/spacedrive
> pnpm core prisma generate


> spacedrive@0.0.0 core /tmp/spacedrive
> pnpm --filter @sd/core --  "prisma" "generate"


> @sd/core@0.0.0 prisma /tmp/spacedrive/core
> cargo prisma "generate"

error: failed to parse manifest at `/tmp/spacedrive/core/Cargo.toml`

Caused by:
  namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
/tmp/spacedrive/core:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @sd/core@0.0.0 prisma: `cargo prisma "generate"`
Exit status 101
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**To Reproduce**
Simply follow the instructions to setup the development environement

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 12.2.1

**Additional context**

```
node -v
v17.9.0

cargo version
cargo 1.59.0
```

**Comment by oscartbeaumont** [comment]
The `dep:` prefix was only just added in the last release of Rust. Can you try running `rustup update` and `rustup toolchain stable` and give the build process another shot.

**Comment by Tchoupinax** [comment]
Hello,

Thank you for your quick answer. It unlocks the issue.

For the record, what I did:

Install rustup here : https://www.rust-lang.org/tools/install


then,
```
rustup update
rustup toolchain install stable
```
