### ISSUE TITLE
Package 'libavresample-dev' has no installation candidate

### ISSUE THREAD

**Issue by sommerper** [spacedriveapp/spacedrive#67]
**Describe the bug**
On PopOS 21.10.
Trying to run setup shell script after cloning repository.

**To Reproduce**
1. git clone https://github.com/spacedriveapp/spacedrive
2. cd spacedrive
3. curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
4. curl -fsSL https://get.pnpm.io/install.sh | PNPM_VERSION=7.0.0-rc.9 sh - 
5. chmod +x ./.github/scripts/setup-system.sh && ./.github/scripts/setup-system.sh 
Results in output:
```
Setting up your system for Spacedrive development!
Detected 'apt' based distro!
[sudo] password for asdasdasd: 
Hit:1 https://download.docker.com/linux/ubuntu impish InRelease
Hit:2 http://ppa.launchpad.net/mosquitto-dev/mosquitto-ppa/ubuntu impish InRelease                       
Hit:3 http://us.archive.ubuntu.com/ubuntu impish InRelease                                               
Get:4 http://us.archive.ubuntu.com/ubuntu impish-security InRelease [110 kB]                
Hit:5 http://apt.pop-os.org/proprietary impish InRelease                                          
Get:6 http://apt.pop-os.org/release impish InRelease [6,850 B]                                    
Get:7 http://us.archive.ubuntu.com/ubuntu impish-updates InRelease [115 kB]                              
Get:8 http://apt.pop-os.org/release impish/main Sources [66.3 kB]                                 
Get:9 http://us.archive.ubuntu.com/ubuntu impish-backports InRelease [101 kB]                   
Hit:10 https://fman.io/updates/ubuntu stable InRelease                                  
Get:11 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 DEP-11 Metadata [20.3 kB]
Get:12 http://us.archive.ubuntu.com/ubuntu impish-security/universe amd64 DEP-11 Metadata [3,624 B]
Get:13 http://us.archive.ubuntu.com/ubuntu impish-updates/main i386 Packages [179 kB]
Get:14 http://us.archive.ubuntu.com/ubuntu impish-updates/main amd64 Packages [384 kB]             
Get:15 http://us.archive.ubuntu.com/ubuntu impish-updates/main amd64 DEP-11 Metadata [25.7 kB]
Get:16 http://us.archive.ubuntu.com/ubuntu impish-updates/universe amd64 DEP-11 Metadata [35.6 kB]
Get:17 http://us.archive.ubuntu.com/ubuntu impish-updates/multiverse amd64 DEP-11 Metadata [940 B]
Get:18 http://us.archive.ubuntu.com/ubuntu impish-backports/universe amd64 DEP-11 Metadata [16.4 kB]
Get:19 http://apt.pop-os.org/release impish/main amd64 Packages [152 kB]                   
Get:20 http://apt.pop-os.org/release impish/main i386 Packages [76.3 kB]
Fetched 1,293 kB in 2s (707 kB/s)                           
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libavresample-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libavresample-dev' has no installation candidate
```
**Expected behavior**
SpaceDrive compiles

**Desktop (please complete the following information):**
```
             /////////////                persommer@atx 
         /////////////////////            ------------- 
      ///////*767////////////////         OS: Pop!_OS 21.10 x86_64 
    //////7676767676*//////////////       Host: MS-7968 3.0 
   /////76767//7676767//////////////      Kernel: 5.17.0-051700-generic 
  /////767676///*76767///////////////     Uptime: 6 days, 11 hours, 57 mins 
 ///////767676///76767.///7676*///////    Packages: 2836 (dpkg), 50 (flatpak), 8 (snap) 
/////////767676//76767///767676////////   Shell: zsh 5.8 
//////////76767676767////76767/////////   Resolution: 3840x2160, 3840x2160, 4384x2466 
///////////76767676//////7676//////////   DE: GNOME 40.5 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: Intel i7-6700K (8) @ 4.200GHz 
    /////767676767676767676767/////       GPU: AMD ATI Radeon RX 6600/6600 XT/6600M 
      ///////////////////////////         Memory: 12372MiB / 15954MiB 
         /////////////////////
             /////////////                                        
                                                                  

```

**Comment by bolshoytoster** [comment]
@sommerper the package [looks to come from](https://packages.ubuntu.com/hirsute/libavresample-dev) the ubuntu ([security]) [universe] repo,  Unfortunately, it's not in the impish repo (the one your popos is using).

You could either add the hirsute [universe] repo in your `/etc/apt/sources.list` (unrecommended) or you can get the package from the previously linked page and install it with `apt install ./filename.deb`, in which case you'll probably also have to install it's dependencies manually.

**Comment by ykabusalah** [comment]
Could I try my hand at trying to solve this? @sommerper @bolshoytoster 
And if so, could you assign me?

**Comment by bolshoytoster** [comment]
@ykabusalah if you mean switching from `libavresample` to `libswresample` then you can. I can't assign you though.

**Comment by oscartbeaumont** [comment]
@bolshoytoster moving away from `libavresample` is pretty out of our control as it's coming from [ffmpeg-next](https://crates.io/crates/ffmpeg-next). If anyone wants to do an upstream fix that would be appreciated but I don't think that it would be an easy change.

I don't really know a good solution to this. I ended up not being able to get the app running in PopOS and decided to add a Rust feature flag to disable ffmpeg as I don't need it for the part of the app I am testing.

**Comment by bolshoytoster** [comment]
@oscartbeaumont I think that as of version 5.0 it's already migrated from `libavresample` - [PR on `ffmpeg-sys-next`](https://github.com/zmwangx/rust-ffmpeg/pull/90) (`ffmpeg-next`'s main dependency).

Could try removing `libavresample-dev` from `.github/scripts/setup-system.sh`.

**Comment by oscartbeaumont** [comment]
It looks like we are already using a version of the crate with that PR merged so maybe give that a shot without that dependency.

**Comment by oscartbeaumont** [comment]
I gave it a shot by removing `libavresample-dev` from the dependencies and it seemed to work on PopOS. I updated the setup script so it doesn't include `libavresample-dev` on PopOS. It would be great if anyone else can give this a test on their machine to confirm it's not something special with my setup.

**Comment by voletro** [comment]
Tested on two PopOS machines, both installed ffmpeg deps and built ffmpeg-rust.
