### ISSUE TITLE
Can Supertag help you in any way?

### ISSUE THREAD

**Issue by amoffat** [spacedriveapp/spacedrive#69]
I wrote [Supertag](https://github.com/amoffat/supertag) in Rust a couple of years ago for fun. It has some innovative ideas around tagging, that I would love to see get picked up by this project. I can't contribute any development time, but I would be happy to help advise in any way that I can, if you're interested. If there's no interest, feel free to close the issue :)

**Comment by oscartbeaumont** [comment]
We will have a look into it. We will probably end up with our own system because of how critical it is to the product but thanks for the suggestion.

**Comment by amoffat** [comment]
No sweat 🙂
