### ISSUE TITLE
I see the fact that the self hosted feature isn't done yet so please make it hostable on windows too,

### ISSUE THREAD

**Issue by AyaanMAG** [spacedriveapp/spacedrive#75]
This project looks like absolute fire and i have my hopes up so PLEASE add the option to host the server version on windows

**Comment by oscartbeaumont** [comment]
There is no reason we can't support it as we are building the backend in Rust. I think if you want native Windows hosting it will be a bit more work to set up and won't be as well documented cause I think we will primarily support Docker for deploying the server. In the end we have limited time and Docker is our best bet to support the host users, with the least hassle.

If you were to use Docker on Windows (which runs Linux under the hood) expect perfect and well-documented support.

I am closing this to clear the issue tracker as it won't require any extra work on our end.
