### ISSUE TITLE
Setup scripts

### ISSUE THREAD

**Issue by oscartbeaumont** [spacedriveapp/spacedrive#77]
- [x] Windows
- [ ] Linux - Arch
- [x] Linux - Ubuntu
- [x] Linux - PopOS
- [x] Linux - Debian
- [ ] Linux - Fedora
- [x] Convert CI to use the script

**Comment by oscartbeaumont** [comment]
- [ ] Windows
- [ ] Linux - Arch
- [ ] Linux - Ubuntu
- [ ] Linux - PopOS
- [ ] Linux - Debian
- [ ] Linux - Fedora

**Comment by kolton-musgrove** [comment]
Could I take care of writing the windows setup script?

I think a logical flow of operations would be:

1. Check for rust, cargo, nodejs, and npnm installations
2. run pnpm i
3. run pnpm prep

Is there other functionality you wanted the scripts to have?

**Comment by oscartbeaumont** [comment]
@kolton-musgrove Feel free to do the Windows setup script!

The functionality you listed sounds good. You will have to install the required Tauri dependencies along with `ffmpeg` or its required dependencies so that the Rust code will build.

**Comment by abhnva** [comment]
What about the Linux script?

**Comment by oscartbeaumont** [comment]
What about them?

The alpha version of the Linux script [already exists in the repo](https://github.com/spacedriveapp/spacedrive/blob/main/.github/scripts/setup-system.sh). I just need to get Arch and Fedora working properly, which is hard as I only have a Debian based system (although imma test with Docker). I have had a busy few days but I will push my changes before mid-week.

**Comment by CodePurble** [comment]
Hi @oscartbeaumont, I'd be happy to help out with the Arch Linux install.

**Comment by voletro** [comment]
I am rewriting the windows setup script, given that so many people are having issues.

From past experience, the ffmpeg binaries are need in path, including each library ffmpeg needs and their respective binaries.

I'll keep updated here and will test with multiple machines.

**Comment by oscartbeaumont** [comment]
Awesome! Feel free to message on here or Discord if you got any questions!
