### ISSUE TITLE
Minimize restore and close buttons are missing on Windows

### ISSUE THREAD

**Issue by Irvingouj** [spacedriveapp/spacedrive#79]
**Describe the bug**
There is no minimize restore and close button on windows

**To Reproduce**
build the project on windows and run pnpm desktop dev. The desktop app will pop up but has no minimize restore and close buttons.

**Expected behavior**
there should be three buttons just as in other apps on Windows, 

**Screenshots**
![success](https://user-images.githubusercontent.com/49964599/166124450-df21fbf2-88d9-4cf2-b88c-17a74146cb16.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by ykabusalah** [comment]
Hello, could I claim this issue?

**Comment by jamiepine** [comment]
consider it claimed

**Comment by ykabusalah** [comment]
Could you check this and see if it works? @jamiepine
