### ISSUE TITLE
Ubuntu 22 build failure: prisma debian-openssl-3.0.x/query-engine.gz not found

### ISSUE THREAD

**Issue by ckgt** [spacedriveapp/spacedrive#81]
**Describe the bug**
Prisma-client can't download. File not found. `pnpm prep` fails building `prisma-client-rust`.

Prisma client downloader picks the system openssl version. Ubuntu 22 repos use openssl 3.0.
Prisma has not released an official openssl 3.0 query-engine build yet. Step fails, can't do prisma generation.

**To Reproduce**
Build on ubuntu 22
node: 16.15 +
npm: 8.5.5 + 

1. Follow [contributing local build steps](https://github.com/spacedriveapp/spacedrive/blob/main/CONTRIBUTING.md#make-changes-locally)
2. `pnpm prep`
3. `prisma-client-rust` fails with `debian-openssl-3.0.x/query-engine.gz` file not found error.

**Expected behavior**
Expected successful compilation of project.

**Desktop:**
 - OS: Ubuntu 22.04 LTS

**Mitigation**

 * Change [this function](https://github.com/Brendonovich/prisma-client-rust/blob/eb7a7804518f68933ce313ae6226b882b22b81f8/cli/src/binaries/platform.rs#L122) to return "1.1.x".
 * Download [Openssl 1.1.1n.tar.gz](https://www.openssl.org/source/openssl-1.1.1n.tar.gz)
 * configure; make; make install    (backup your libssl.so and libcrypto.so symlinks before)
 * Make sure the libssl.so.1.1 and libcrypto.so.1.1 objects are symlinked in your system lib folder for libssl.so and libcrypto.so. Make sure to undo this when you're done.

You should link against the 1.1 .a libs instead for a more permanent solution.

**Comment by Brendonovich** [comment]
Moving to [Prisma Client Rust](https://github.com/Brendonovich/prisma-client-rust/issues/52)
