### ISSUE TITLE
White Square On Horizontal Scroll

### ISSUE THREAD

**Issue by Soft-Bred** [spacedriveapp/spacedrive#855]
### Describe the bug

When a horizontal scroll bar is necessary, a white square appears in the intersection between the vertical and horizontal scroll.

https://github.com/spacedriveapp/spacedrive/assets/60551230/97e3c63b-a635-420d-ab8a-8be03b2cbac6

### Reproduction

1. go to overview
2. switch to list view
3. Reduce width of window to enable horizontal scroll.

### Expected behavior

This doesn't happen.

### Platform and versions

```Shell
`pnpm --version && cargo --version && rustc --version`:
9.6.6

OS:
macOS 12.6.2 21G320 arm64

Chip:
Apple M1 Max

Spacedrive Version:
v0.1.0 - 2325a8c
```

**Comment by HeavenVolkoff** [comment]
Can confirm this is also happening on Linux:

![Screenshot from 2023-05-24 14-23-00](https://github.com/spacedriveapp/spacedrive/assets/9082460/9c530677-bf85-4e08-91a9-12d9e3ad379e)

**Comment by HeavenVolkoff** [comment]
Also on web version:

![Screenshot from 2023-05-24 14-27-05](https://github.com/spacedriveapp/spacedrive/assets/9082460/00f22c13-e952-444c-b502-25a2a9fcde59)
