### ISSUE TITLE
[MacOS] Incorrect Borders On Right Corners In Overview 

### ISSUE THREAD

**Issue by Soft-Bred** [spacedriveapp/spacedrive#857]
### Describe the bug

The bottom right and top right corners seem the have the window's border not curve, as seen on the left. This only happens on overview page.

![004606@2x](https://github.com/spacedriveapp/spacedrive/assets/60551230/42fc7833-e535-4379-b68f-73a30f89c3d4)

<img width="50" alt="004607@2x" src="https://github.com/spacedriveapp/spacedrive/assets/60551230/4e2b879e-e31f-4924-b1e3-560a5088518e">
<img width="46" alt="004608@2x" src="https://github.com/spacedriveapp/spacedrive/assets/60551230/6f5dc39c-4bdb-4a5f-ae17-56257b138884">

### Reproduction

1. Go to Overview
2. Look at top and bottom right corners (looks different)
3. look at top and bottom left corners (correct)

### Expected behavior

Corners should look like left side corners

### Platform and versions

```Shell
`pnpm --version && cargo --version && rustc --version`:
9.6.6

OS:
macOS 12.6.2 21G320 arm64

Chip:
Apple M1 Max

Spacedrive Version:
v0.1.0 - 2325a8c
```

**Comment by FastestMolasses** [comment]
Can you still reproduce this? I cant on the latest main branch. Maybe it was fixed already?

**Comment by Raghav-45** [comment]
hey @utkubakir unfortunatly i don't have mac, so i think we can close this issue if it is solved
