### ISSUE TITLE
[MacOS] Color picker on "New tag" doesn't allow for dragging.

### ISSUE THREAD

**Issue by jamesjroddie** [spacedriveapp/spacedrive#904]
### Describe the bug

When using the color picker to create a new tag, your first click is what it selects. There's no ability to drag either the hue slider or the saturation/lightness. This means the first click you do makes a selection and closes the picker window. 

### Reproduction

1. Go to a file 
2. Right click and select "Assign tag" -> "New tag"
3. Open the color selector 
4. Click and attempt to drag

### Expected behavior

When selecting a color, I would expect that I can drag the selectors around to see how it impacts my choice. 

### Platform and versions

```Shell
pnpm: 8.6.0
cargo: 1.69.0 (6e9a83356 2023-04-12)
rustc: 1.69.0 (84c898d65 2023-04-16)


OS:
macOS 12.4 arm64

Chip:
Apple M1 Max

Spacedrive Version:
v0.1.0 - 94c9805
```

**Comment by utkubakir** [comment]
I am pretty sure this is fixed, feel free to re-open the issue if that isn't the case.
