### ISSUE TITLE
[MacOS] Dragging a file engages multiple operations

### ISSUE THREAD

**Issue by jamesjroddie** [spacedriveapp/spacedrive#906]
### Describe the bug

When trying to move a file/folder, a couple of operations occur at the same time. 

1. Draggable multi-select 
2. Space Drop

Due to the other actions, it's not possible to drag and drop to move a file/folder.

### Reproduction

1. Try to drag and drop any file/folder

https://github.com/spacedriveapp/spacedrive/assets/104273002/f62177f9-5b49-4a48-81ad-e648f4c12f5f

### Expected behavior

When the cursor is hovering over a file/folder it should allow me to drag & drop where I would like rather than trying to multi-select. 

### Platform and versions

```Shell
pnpm: 8.6.0
cargo: 1.69.0 (6e9a83356 2023-04-12)
rustc: 1.69.0 (84c898d65 2023-04-16)

OS:
macOS 12.4 arm64

Chip:
Apple M1 Max

Spacedrive Version:
v0.1.0 - 94c9805
```

**Comment by jamesjroddie** [comment]
I can no longer multi-select, but Space drop is still engaged when dragging and dropping.

**Comment by oscartbeaumont** [comment]
I am fairly sure this will have been fixed when Spacedrop was disabled yesterday.

**Comment by jamesjroddie** [comment]
I used the latest build and I can't multi-select anymore. Even with Shift, CMD, etc.

**Comment by utkubakir** [comment]
> I used the latest build and I can't multi-select anymore. Even with Shift, CMD, etc.

I think we disabled multi-select because the backend wasn't there yet.
